///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PalletIdHistoryModel {
  String palletID;
  String soCode;
  String oldBin;
  String newBin;
  String createDate;
  String createdBy;


  PalletIdHistoryModel({
    required this.oldBin,
    required this.createdBy,
    required this.createDate,
    required this.newBin,
    required this.palletID,
    required this.soCode,
  });

  factory PalletIdHistoryModel.fromJson(List<dynamic> json) {
    return PalletIdHistoryModel(
      oldBin: json[1]?.toString() ?? '',
      createdBy: json[10]?.toString() ?? '',
      createDate: json[10]?.toString() ?? '',
      newBin: json[10]?.toString() ?? '',
      palletID: json[10]?.toString() ?? '',
      soCode: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['oldBin'] = oldBin;
    data['createdBy'] = createdBy;
    data['createDate'] = createDate;
    data['newBin'] = newBin;
    data['palletID'] = palletID;
    data['soCode'] = soCode;
    return data;
  }
}
