///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PackageReceiptModel {
  String action;
  String packageType;
  String condition;
  String trackingNumber;
  String leftAt;
  String leftWith;
  String createdDate;
  String createdBy;
  String fileList;


  PackageReceiptModel({
    required this.fileList,
    required this.condition,
    required this.packageType,
    required this.leftWith,
    required this.trackingNumber,
    required this.createdDate,
    required this.action,
    required this.createdBy,
    required this.leftAt,
  });

  factory PackageReceiptModel.fromJson(List<dynamic> json) {
    return PackageReceiptModel(
      action: json[28]?.toString() ?? '',
      fileList: json[4]?.toString() ?? '',
      condition: json[14]?.toString() ?? '',
      packageType: json[8]?.toString() ?? '',
      leftWith: json[26]?.toString() ?? '',
      trackingNumber: json[23]?.toString() ?? '',
      createdDate: json[3]?.toString() ?? '',
      createdBy: json[18]?.toString() ?? '',
      leftAt: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fileList'] = fileList;
    data['condition'] = condition;
    data['packageType'] = packageType;
    data['leftWith'] = leftWith;
    data['trackingNumber'] = trackingNumber;
    data['createdDate'] = createdDate;
    data['action'] = action;
    data['createdBy'] = createdBy;
    data['leftAt'] = leftAt;
    return data;
  }
}
