///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CompletedContainersModel {
  String loc;
  String urgent;
  String container;
  String containerItemType;
  String dock;
  String yardStatus;
  String memoInYard;
  String receiveStart;
  String memo;
  String receiveStartBy;
  String scanCompletedBy;
  String scanCompletedDate;
  String dateInYard;
  String inYardBy;
  String inYardDate;
  String vendor;
  String po;
  String invoiceDate;
  String etaWarehouse;
  String etaPort;
  String inv;
  String lfd;
  
  CompletedContainersModel({
    required this.vendor,
    required this.urgent,
    required this.etaPort,
    required this.container,
    required this.lfd,
    required this.inYardBy,
    required this.inv,
    required this.scanCompletedBy,
    required this.etaWarehouse,
    required this.memoInYard,
    required this.dateInYard,
    required this.memo,
    required this.invoiceDate,
    required this.scanCompletedDate,
    required this.loc,
    required this.po,
    required this.inYardDate,
    required this.receiveStartBy,
    required this.receiveStart,
    required this.yardStatus,
    required this.dock,
    required this.containerItemType,
  });

  factory CompletedContainersModel.fromJson(List<dynamic> json) {
    return CompletedContainersModel(
      urgent: json[1]?.toString() ?? '',
      container: json[2]?.toString() ?? '',
      vendor: json[3]?.toString() ?? '',
      lfd: json[6]?.toString() ?? '',
      inYardBy: json[5]?.toString() ?? '',
      inv: json[7]?.toString() ?? '',
      etaPort: json[8]?.toString() ?? '',
      scanCompletedBy: json[11]?.toString() ?? '',
      etaWarehouse: json[10]?.toString() ?? '',
      memoInYard: json[10]?.toString() ?? '',
      dateInYard: json[10]?.toString() ?? '',
      memo: json[10]?.toString() ?? '',
      invoiceDate: json[10]?.toString() ?? '',
      scanCompletedDate: json[10]?.toString() ?? '',
      loc: json[10]?.toString() ?? '',
      inYardDate: json[10]?.toString() ?? '',
      po: json[10]?.toString() ?? '',
      receiveStartBy: json[10]?.toString() ?? '',
      receiveStart: json[10]?.toString() ?? '',
      yardStatus: json[10]?.toString() ?? '',
      dock: json[10]?.toString() ?? '',
      containerItemType: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['vendor'] = vendor;
    data['urgent'] = urgent;
    data['etaPort'] = etaPort;
    data['container'] = container;
    data['lfd'] = lfd;
    data['inYardBy'] = inYardBy;
    data['inv'] = inv;
    data['scanCompletedBy'] = scanCompletedBy;
    data['etaWarehouse'] = etaWarehouse;
    data['memoInYard'] = memoInYard;
    data['dateInYard'] = dateInYard;
    data['memo'] = memo;
    data['invoiceDate'] = invoiceDate;
    data['scanCompletedDate'] = scanCompletedDate;
    data['loc'] = loc;
    data['po'] = po;
    data['inYardDate'] = inYardDate;
    data['receiveStartBy'] = receiveStartBy;
    data['receiveStart'] = receiveStart;
    data['yardStatus'] = yardStatus;
    data['dock'] = dock;
    data['containerItemType'] = containerItemType;
    return data;
  }
}
