///
/// Code generated by jsonwarehouseDartModel https://ashamp.github.io/jsonwarehouseDartModel/
///
class ManifestHistoryModel {
  String warehouse;
  String mileage;
  String terms;
  String so;
  String orderType;
  String customer;
  String eMail;
  String totalWeight;
  String shipDate;
  String receivingHours;
  String gateType;
  String shipMethod;
  String category;
  String pastDue;
  String appt;
  String address;
  String boxCount;
  String palletCount;
  String hours;
  String pickedBy;
  String checkedBy;
  String companyBusinessName;
  String contactPerson;
  String phone;
  String zone;
  String trailerAccess;
  String loadingDock;
  String liftGate;
  String limitedAccess;
  String customerNotes;
  String departureSchedule;
  String stopTimeStamp;
  String driveDuration;
  String driverNotes;
  String loader;
  String priority;
  String confirmedAppt;
  String route;
  String stop;
  String trailer;
  String stopDuration;
  String palletExchange;
  String truck;
  String truckType;
  String pod;
  String driver;
  String totalRouteTimer;
  String palletJack;
  String startTimeStamp;

  ManifestHistoryModel({
    required this.pastDue,
    required this.mileage,
    required this.palletCount,
    required this.terms,
    required this.pickedBy,
    required this.shipMethod,
    required this.hours,
    required this.boxCount,
    required this.eMail,
    required this.gateType,
    required this.shipDate,
    required this.address,
    required this.warehouse,
    required this.appt,
    required this.category,
    required this.receivingHours,
    required this.totalWeight,
    required this.customer,
    required this.so,
    required this.orderType,
    required this.loadingDock,
    required this.driverNotes,
    required this.stopTimeStamp,
    required this.companyBusinessName,
    required this.trailerAccess,
    required this.phone,
    required this.departureSchedule,
    required this.customerNotes,
    required this.liftGate,
    required this.zone,
    required this.contactPerson,
    required this.checkedBy,
    required this.loader,
    required this.driveDuration,
    required this.limitedAccess,
    required this.palletJack,
    required this.driver,
    required this.priority,
    required this.trailer,
    required this.route,
    required this.pod,
    required this.truckType,
    required this.palletExchange,
    required this.stop,
    required this.confirmedAppt,
    required this.stopDuration,
    required this.startTimeStamp,
    required this.totalRouteTimer,
    required this.truck,
  });

  factory ManifestHistoryModel.fromJson(List<dynamic> json) {
    return ManifestHistoryModel(
      mileage: json[1]?.toString() ?? '',
      terms: json[2]?.toString() ?? '',
      pastDue: json[3]?.toString() ?? '',
      pickedBy: json[6]?.toString() ?? '',
      shipMethod: json[5]?.toString() ?? '',
      hours: json[7]?.toString() ?? '',
      palletCount: json[8]?.toString() ?? '',
      boxCount: json[10]?.toString() ?? '',
      eMail: json[10]?.toString() ?? '',
      gateType: json[10]?.toString() ?? '',
      shipDate: json[10]?.toString() ?? '',
      address: json[10]?.toString() ?? '',
      warehouse: json[10]?.toString() ?? '',
      category: json[10]?.toString() ?? '',
      appt: json[10]?.toString() ?? '',
      receivingHours: json[10]?.toString() ?? '',
      totalWeight: json[10]?.toString() ?? '',
      customer: json[10]?.toString() ?? '',
      so: json[10]?.toString() ?? '',
      orderType: json[10]?.toString() ?? '',
      driverNotes: json[7]?.toString() ?? '',
      driveDuration: json[8]?.toString() ?? '',
      stopTimeStamp: json[10]?.toString() ?? '',
      companyBusinessName: json[10]?.toString() ?? '',
      trailerAccess: json[10]?.toString() ?? '',
      phone: json[10]?.toString() ?? '',
      departureSchedule: json[10]?.toString() ?? '',
      loader: json[10]?.toString() ?? '',
      liftGate: json[10]?.toString() ?? '',
      customerNotes: json[10]?.toString() ?? '',
      zone: json[10]?.toString() ?? '',
      contactPerson: json[10]?.toString() ?? '',
      checkedBy: json[10]?.toString() ?? '',
      loadingDock: json[10]?.toString() ?? '',
      limitedAccess: json[10]?.toString() ?? '',
      totalRouteTimer: json[8]?.toString() ?? '',
      driver: json[10]?.toString() ?? '',
      priority: json[10]?.toString() ?? '',
      trailer: json[10]?.toString() ?? '',
      route: json[10]?.toString() ?? '',
      pod: json[10]?.toString() ?? '',
      startTimeStamp: json[10]?.toString() ?? '',
      palletExchange: json[10]?.toString() ?? '',
      truckType: json[10]?.toString() ?? '',
      stop: json[10]?.toString() ?? '',
      confirmedAppt: json[10]?.toString() ?? '',
      palletJack: json[10]?.toString() ?? '',
      stopDuration: json[10]?.toString() ?? '',
      truck: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> warehouseJson() {
    final data = <String, dynamic>{};
    data['pastDue'] = pastDue;
    data['mileage'] = mileage;
    data['palletCount'] = palletCount;
    data['terms'] = terms;
    data['pickedBy'] = pickedBy;
    data['shipMethod'] = shipMethod;
    data['hours'] = hours;
    data['boxCount'] = boxCount;
    data['eMail'] = eMail;
    data['gateType'] = gateType;
    data['shipDate'] = shipDate;
    data['address'] = address;
    data['warehouse'] = warehouse;
    data['appt'] = appt;
    data['category'] = category;
    data['receivingHours'] = receivingHours;
    data['totalWeight'] = totalWeight;
    data['customer'] = customer;
    data['so'] = so;
    data['orderType'] = orderType;
    data['loadingDock'] = loadingDock;
    data['driverNotes'] = driverNotes;
    data['stopTimeStamp'] = stopTimeStamp;
    data['companyBusinessName'] = companyBusinessName;
    data['trailerAccess'] = trailerAccess;
    data['phone'] = phone;
    data['departureSchedule'] = departureSchedule;
    data['driveDuration'] = driveDuration;
    data['customerNotes'] = customerNotes;
    data['liftGate'] = liftGate;
    data['zone'] = zone;
    data['contactPerson'] = contactPerson;
    data['checkedBy'] = checkedBy;
    data['loader'] = loader;
    data['truck'] = truck;
    data['palletJack'] = palletJack;
    data['driver'] = driver;
    data['priority'] = priority;
    data['trailer'] = trailer;
    data['route'] = route;
    data['pod'] = pod;
    data['totalRouteTimer'] = totalRouteTimer;
    data['truckType'] = truckType;
    data['palletExchange'] = palletExchange;
    data['stop'] = stop;
    data['confirmedAppt'] = confirmedAppt;
    data['stopDuration'] = stopDuration;
    data['startTimeStamp'] = startTimeStamp;
    data['limitedAccess'] = limitedAccess;
    return data;
  }
}
