///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SPPackingHistoryModel {
  String pickUpDate;
  String deliveryDate;
  String salesOrd;
  String action;
  String po;
  String customerName;
  String warehouse;
  String shipZipcode;
  String carrier;
  String boxType;
  String trackNo;
  String rate;
  String signatureCost;
  String status;
  String packStartBy;
  String packStartDate;
  String weight;
  String duration;
  String shipToAddress;
  String orderStatus;
  String kpPage;
  String fulfillmentBy;
  String fulfillmentDate;
  String reshipment;
  String length;
  String width;
  String height;

  SPPackingHistoryModel({
    required this.weight,
    required this.salesOrd,
    required this.shipZipcode,
    required this.trackNo,
    required this.signatureCost,
    required this.status,
    required this.packStartBy,
    required this.packStartDate,
    required this.rate,
    required this.pickUpDate,
    required this.deliveryDate,
    required this.carrier,
    required this.action,
    required this.boxType,
    required this.duration,
    required this.shipToAddress,
    required this.orderStatus,
    required this.warehouse,
    required this.customerName,
    required this.po,
    required this.kpPage,
    required this.fulfillmentBy,
    required this.fulfillmentDate,
    required this.reshipment,
    required this.length,
    required this.width,
    required this.height,
  });

  factory SPPackingHistoryModel.fromJson(List<dynamic> json) {
    return SPPackingHistoryModel(
      action: json[28]?.toString() ?? '',
      salesOrd: json[28]?.toString() ?? '',
      weight: json[4]?.toString() ?? '',
      shipZipcode: json[14]?.toString() ?? '',
      trackNo: json[0]?.toString() ?? '',
      signatureCost: json[15]?.toString() ?? '',
      status: json[6]?.toString() ?? '',
      packStartBy: json[7]?.toString() ?? '',
      packStartDate: json[8]?.toString() ?? '',
      rate: json[12]?.toString() ?? '',
      pickUpDate: json[26]?.toString() ?? '',
      deliveryDate: json[26]?.toString() ?? '',
      carrier: json[3]?.toString() ?? '',
      boxType: json[18]?.toString() ?? '',
      duration: json[23]?.toString() ?? '',
      shipToAddress: json[3]?.toString() ?? '',
      orderStatus: json[18]?.toString() ?? '',
      warehouse: json[18]?.toString() ?? '',
      customerName: json[18]?.toString() ?? '',
      po: json[18]?.toString() ?? '',
      kpPage: json[18]?.toString() ?? '',
      fulfillmentBy: json[18]?.toString() ?? '',
      fulfillmentDate: json[18]?.toString() ?? '',
      reshipment: json[18]?.toString() ?? '',
      length: json[18]?.toString() ?? '',
      width: json[18]?.toString() ?? '',
      height: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['weight'] = weight;
    data['salesOrd'] = salesOrd;
    data['shipZipcode'] = shipZipcode;
    data['trackNo'] = trackNo;
    data['signatureCost'] = signatureCost;
    data['status'] = status;
    data['packStartBy'] = packStartBy;
    data['packStartDate'] = packStartDate;
    data['rate'] = rate;
    data['pickUpDate'] = pickUpDate;
    data['deliveryDate'] = deliveryDate;
    data['carrier'] = carrier;
    data['action'] = action;
    data['boxType'] = boxType;
    data['duration'] = duration;
    data['shipToAddress'] = shipToAddress;
    data['orderStatus'] = orderStatus;
    data['warehouse'] = warehouse;
    data['customerName'] = customerName;
    data['po'] = po;
    data['kpPage'] = kpPage;
    data['fulfillmentBy'] = kpPage;
    data['fulfillmentDate'] = fulfillmentDate;
    data['reshipment'] = reshipment;
    data['length'] = length;
    data['width'] = width;
    data['height'] = height;
    return data;
  }
}
