///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RoutePrepListModel {
  String shipAddress1;
  String shipAddress2;
  String shipCity;
  String shipState;
  String shipZipCode;
  String route;

  RoutePrepListModel({
    required this.shipAddress2,
    required this.shipCity,
    required this.route,
    required this.shipAddress1,
    required this.shipZipCode,
    required this.shipState,
  });

  factory RoutePrepListModel.fromJson(List<dynamic> json) {
    return RoutePrepListModel(
      shipAddress2: json[1]?.toString() ?? '',
      shipCity: json[2]?.toString() ?? '',
      route: json[10]?.toString() ?? '',
      shipAddress1: json[10]?.toString() ?? '',
      shipZipCode: json[10]?.toString() ?? '',
      shipState: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['shipAddress2'] = shipAddress2;
    data['shipCity'] = shipCity;
    data['route'] = route;
    data['shipAddress1'] = shipAddress1;
    data['shipZipCode'] = shipZipCode;
    data['shipState'] = shipState;
    return data;
  }
}
