///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RoutePrepListExpansionModel {
  String route;
  String customerName;
  String so;
  String dockLoading;
  String category;
  String appt;
  String address;
  String hours;
  String companyBusinessName;
  String phone;
  String zone;
  String contactPerson;
  String trailerAccess;
  String liftGate;
  String limitedAccess;

  RoutePrepListExpansionModel({
    required this.customerName,
    required this.hours,
    required this.address,
    required this.route,
    required this.appt,
    required this.category,
    required this.so,
    required this.dockLoading,
    required this.companyBusinessName,
    required this.trailerAccess,
    required this.phone,
    required this.liftGate,
    required this.zone,
    required this.contactPerson,
    required this.limitedAccess,
  });

  factory RoutePrepListExpansionModel.fromJson(List<dynamic> json) {
    return RoutePrepListExpansionModel(
      customerName: json[2]?.toString() ?? '',
      hours: json[7]?.toString() ?? '',
      address: json[10]?.toString() ?? '',
      route: json[10]?.toString() ?? '',
      category: json[10]?.toString() ?? '',
      appt: json[10]?.toString() ?? '',
      so: json[10]?.toString() ?? '',
      dockLoading: json[10]?.toString() ?? '',
      companyBusinessName: json[10]?.toString() ?? '',
      trailerAccess: json[10]?.toString() ?? '',
      phone: json[10]?.toString() ?? '',
      liftGate: json[10]?.toString() ?? '',
      zone: json[10]?.toString() ?? '',
      contactPerson: json[10]?.toString() ?? '',
      limitedAccess: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['customerName'] = customerName;
    data['hours'] = hours;
    data['address'] = address;
    data['route'] = route;
    data['appt'] = appt;
    data['category'] = category;
    data['so'] = so;
    data['dockLoading'] = dockLoading;
    data['companyBusinessName'] = companyBusinessName;
    data['trailerAccess'] = trailerAccess;
    data['phone'] = phone;
    data['liftGate'] = liftGate;
    data['zone'] = zone;
    data['contactPerson'] = contactPerson;
    data['limitedAccess'] = limitedAccess;
    return data;
  }
}
