///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LPNReprintReviewModel {
  String warehouse;
  String lpn;
  String bin;
  String itemCode;
  String legacyItem;
  String qty;
  String reprintBy;
  String reprintDate;


  LPNReprintReviewModel({
    required this.bin,
    required this.lpn,
    required this.qty,
    required this.itemCode,
    required this.reprintBy,
    required this.warehouse,
    required this.reprintDate,
    required this.legacyItem,
  });

  factory LPNReprintReviewModel.fromJson(List<dynamic> json) {
    return LPNReprintReviewModel(
      warehouse: json[28]?.toString() ?? '',
      bin: json[14]?.toString() ?? '',
      lpn: json[8]?.toString() ?? '',
      qty: json[26]?.toString() ?? '',
      itemCode: json[23]?.toString() ?? '',
      reprintBy: json[3]?.toString() ?? '',
      reprintDate: json[18]?.toString() ?? '',
      legacyItem: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['lpn'] = lpn;
    data['qty'] = qty;
    data['itemCode'] = itemCode;
    data['reprintBy'] = reprintBy;
    data['warehouse'] = warehouse;
    data['reprintDate'] = reprintDate;
    data['legacyItem'] = legacyItem;
    return data;
  }
}
