///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LPNReprintReviewExpansionModel {
  String quantity;
  String memo;
  String bin;
  String reason;
  String updateBy;
  String updateDate;


  LPNReprintReviewExpansionModel({
    required this.bin,
    required this.memo,
    required this.reason,
    required this.updateBy,
    required this.quantity,
    required this.updateDate,
  });

  factory LPNReprintReviewExpansionModel.fromJson(List<dynamic> json) {
    return LPNReprintReviewExpansionModel(
      quantity: json[28]?.toString() ?? '',
      bin: json[14]?.toString() ?? '',
      memo: json[8]?.toString() ?? '',
      reason: json[23]?.toString() ?? '',
      updateBy: json[3]?.toString() ?? '',
      updateDate: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['memo'] = memo;
    data['reason'] = reason;
    data['updateBy'] = updateBy;
    data['quantity'] = quantity;
    data['updateDate'] = updateDate;
    return data;
  }
}
