///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RackReplenishmentModel {
  String wareHouse;
  String bin;
  String quantity;
  String rackItemCategories;


  RackReplenishmentModel({
    required this.quantity,
    required this.bin,
    required this.rackItemCategories,
    required this.wareHouse,
  });

  factory RackReplenishmentModel.fromJson(List<dynamic> json) {
    return RackReplenishmentModel(
      wareHouse: json[28]?.toString() ?? '',
      quantity: json[14]?.toString() ?? '',
      bin: json[8]?.toString() ?? '',
      rackItemCategories: json[23]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['quantity'] = quantity;
    data['bin'] = bin;
    data['rackItemCategories'] = rackItemCategories;
    data['wareHouse'] = wareHouse;
    return data;
  }
}
