name: kp_admin
description: "KPAdmin"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # 收缩菜单
  flutter_admin_scaffold: ^1.3.0
  # 表格
  operance_datatable: ^1.0.7
  # 国际化支持
  intl: ^0.18.1
  # 屏幕适配
  flutter_screenutil: ^5.9.0
  # 动态权限
  permission_handler: ^11.3.1
  # 设备信息
  device_info_plus: ^10.1.0
  # 应用信息
  package_info_plus: ^8.0.2
  # 本地存储
  shared_preferences: ^2.2.2
  # 网络请求
  dio: ^5.4.2+1
  http: ^1.2.2
  # 加载动画
  flutter_easyloading: ^3.0.5
  # svg
  flutter_svg: ^2.0.10+1
  # 时间格式化
  date_format: ^2.0.7
  # 全局事件
  event_bus: ^2.0.0
  # 步骤显示
  linear_progress_bar: any
  # 日历
  calendar_date_picker2: any
  # 选择文件
  file_picker: any
  # 下拉框
  dropdown_search: any
  drop_down_list: any
  # PDF
  flutter_cached_pdfview: any
  # 扫描
  ai_barcode_scanner: any

  path_provider: any
  share_plus: any
  # 瀑布流
  flutter_staggered_grid_view: ^0.7.0
  # 计步器
  cart_stepper: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/



