///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PalletQuantityModel {
  String warehouse;
  String item;
  String legacy;
  String createdDate;
  String qty;


  PalletQuantityModel({
    required this.createdDate,
    required this.item,
    required this.qty,
    required this.warehouse,
    required this.legacy,
  });

  factory PalletQuantityModel.fromJson(List<dynamic> json) {
    return PalletQuantityModel(
      warehouse: json[28]?.toString() ?? '',
      createdDate: json[26]?.toString() ?? '',
      item: json[23]?.toString() ?? '',
      qty: json[3]?.toString() ?? '',
      legacy: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createdDate'] = createdDate;
    data['item'] = item;
    data['qty'] = qty;
    data['warehouse'] = warehouse;
    data['legacy'] = legacy;
    return data;
  }
}
