///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class YardManagmentExpansionModel {
  String legacyItem;
  String scannedQty;
  String ordDate;
  String memo;
  String weight;
  String cubic;
  String upcCode;
  String description;
  String balance;
  String itemCode;
  String qrdQty;


  YardManagmentExpansionModel({
    required this.scannedQty,
    required this.legacyItem,
    required this.ordDate,
    required this.memo,
    required this.weight,
    required this.cubic,
    required this.upcCode,
    required this.description,
    required this.balance,
    required this.itemCode,
    required this.qrdQty,
  });

  factory YardManagmentExpansionModel.fromJson(List<dynamic> json) {
    return YardManagmentExpansionModel(
      legacyItem: json[1]?.toString() ?? '',
      ordDate: json[2]?.toString() ?? '',
      scannedQty: json[3]?.toString() ?? '',
      memo: json[6]?.toString() ?? '',
      weight: json[10]?.toString() ?? '',
      cubic: json[10]?.toString() ?? '',
      upcCode: json[10]?.toString() ?? '',
      description: json[10]?.toString() ?? '',
      balance: json[10]?.toString() ?? '',
      itemCode: json[10]?.toString() ?? '',
      qrdQty: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['scannedQty'] = scannedQty;
    data['legacyItem'] = legacyItem;
    data['ordDate'] = ordDate;
    data['memo'] = memo;
    data['weight'] = weight;
    data['cubic'] = cubic;
    data['upcCode'] = upcCode;
    data['description'] = description;
    data['balance'] = balance;
    data['itemCode'] = itemCode;
    data['qrdQty'] = qrdQty;
    return data;
  }
}
