///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BinSnapshotModel {
  String bin;
  String binType;
  String area;
  String itemCode;
  String legacyItem;
  String po;
  String quantity;
  String container;
  String origin;
  String binUpdatedBy;
  String description;
  String lpn;
  String createdBy;
  String warehouse;
  String lot;
  String binUpdateDate;
  String createDate;
  String sqFT;
  String cube;


  BinSnapshotModel({
    required this.container,
    required this.itemCode,
    required this.legacyItem,
    required this.origin,
    required this.binUpdatedBy,
    required this.area,
    required this.po,
    required this.quantity,
    required this.bin,
    required this.binType,
    required this.description,
    required this.lpn,
    required this.createdBy,
    required this.warehouse,
    required this.lot,
    required this.binUpdateDate,
    required this.createDate,
    required this.sqFT,
    required this.cube,
  });

  factory BinSnapshotModel.fromJson(List<dynamic> json) {
    return BinSnapshotModel(
      itemCode: json[1]?.toString() ?? '',
      legacyItem: json[14]?.toString() ?? '',
      bin: json[8]?.toString() ?? '',
      binType: json[3]?.toString() ?? '',
      area: json[11]?.toString() ?? '',
      po: json[29]?.toString() ?? '',
      quantity: json[30]?.toString() ?? '',
      container: json[31]?.toString() ?? '',
      origin: json[4]?.toString() ?? '',
      binUpdatedBy: json[32]?.toString() ?? '',
      description: json[6]?.toString() ?? '',
      lpn: json[6]?.toString() ?? '',
      createdBy: json[6]?.toString() ?? '',
      warehouse: json[6]?.toString() ?? '',
      lot: json[6]?.toString() ?? '',
      binUpdateDate: json[6]?.toString() ?? '',
      createDate: json[6]?.toString() ?? '',
      sqFT: json[6]?.toString() ?? '',
      cube: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['container'] = container;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['origin'] = origin;
    data['binUpdatedBy'] = binUpdatedBy;
    data['area'] = area;
    data['po'] = po;
    data['quantity'] = quantity;
    data['bin'] = bin;
    data['binType'] = binType;
    data['lpn'] = lpn;
    data['createdBy'] = createdBy;
    data['warehouse'] = warehouse;
    data['lot'] = lot;
    data['binUpdateDate'] = binUpdateDate;
    data['createDate'] = createDate;
    data['sqFT'] = sqFT;
    data['cube'] = cube;
    return data;
  }
}
