///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ScanHistoryModel {
  String license;
  String bpn;
  String origin;
  String holdStatus;
  String loc;
  String itemID;
  String legacyItem;
  String soto;
  String receivedQty;
  String currentQty;
  String bin;
  String customerHold;
  String updateDate;
  String description;
  String binType;
  String createDate;
  String expirationDate;
  String receivedBy;
  String po;
  String container;
  String lastReason;
  String reason;
  String reprintedBy;
  String reprintedDate;
  String reprintedCount;
  String palletQty;
  String lot;
  String unLoader;


  ScanHistoryModel({
    required this.license,
    required this.bpn,
    required this.origin,
    required this.holdStatus,
    required this.loc,
    required this.itemID,
    required this.legacyItem,
    required this.soto,
    required this.receivedQty,
    required this.currentQty,
    required this.bin,
    required this.customerHold,
    required this.updateDate,
    required this.description,
    required this.binType,
    required this.createDate,
    required this.expirationDate,
    required this.receivedBy,
    required this.po,
    required this.container,
    required this.lastReason,
    required this.reason,
    required this.reprintedBy,
    required this.reprintedDate,
    required this.reprintedCount,
    required this.palletQty,
    required this.lot,
    required this.unLoader,

  });

  factory ScanHistoryModel.fromJson(Map<String, dynamic> json) {
    return ScanHistoryModel(
      license: json['ScanID']?.toString() ?? '',
      bpn: json['BPN']?.toString() ?? '',
      origin: json['Origin']?.toString() ?? '',
      holdStatus: json['HoldStatus']?.toString() ?? '',
      loc: json['WareHouseCode']?.toString() ?? '',
      itemID: json['item_code']?.toString() ?? '',
      legacyItem: json['LegacyItem']?.toString() ?? '',
      soto: json['soto']?.toString() ?? '',
      receivedQty: json['ReceiveQuantity']?.toString() ?? '',
      currentQty: json['Quantity']?.toString() ?? '',
      bin: json['Bin']?.toString() ?? '',
      customerHold: json['CustomerHold']?.toString() ?? '',
      updateDate: json['UpdDate']?.toString() ?? '',
      description: json['item_description']?.toString() ?? '',
      binType: json['BinType']?.toString() ?? '',
      createDate: json['CreateDate']?.toString() ?? '',
      expirationDate: json['ExpirationDate']?.toString() ?? '',
      receivedBy: json['CreatedBy']?.toString() ?? '',
      po: json['PO']?.toString() ?? '',
      container: json['Container']?.toString() ?? '',
      lastReason: json['LastReason']?.toString() ?? '',
      reason: json['Reason']?.toString() ?? '',
      reprintedBy: json['ReprintedBy']?.toString() ?? '',
      reprintedDate: json['ReprintedDate']?.toString() ?? '',
      reprintedCount: json['ReprintCount']?.toString() ?? '',
      palletQty: json['PalletQty']?.toString() ?? '',
      lot: json['LotNumber']?.toString() ?? '',
      unLoader: json['Unloader']?.toString() ?? '',

    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bpn'] = bpn;
    data['origin'] = origin;
    data['holdStatus'] = holdStatus;
    data['loc'] = loc;
    data['itemID'] = itemID;
    data['legacyItem'] = legacyItem;
    data['soto'] = soto;
    data['receivedQty'] = receivedQty;
    data['currentQty'] = currentQty;
    data['bin'] = bin;
    data['customerHold'] = customerHold;
    data['updateDate'] = updateDate;
    data['description'] = description;
    data['binType'] = binType;
    data['createDate'] = createDate;
    data['expirationDate'] = expirationDate;
    data['receivedBy'] = receivedBy;
    data['po'] = po;
    data['container'] = container;
    data['lastReason'] = lastReason;
    data['reason'] = reason;
    data['reprintedBy'] = reprintedBy;
    data['reprintedDate'] = reprintedDate;
    data['reprintedCount'] = reprintedCount;
    data['palletQty'] = palletQty;
    data['lot'] = lot;
    data['unLoader'] = unLoader;
    data['license'] = license;
    return data;
  }
}
