///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CycleCountV2BulkListModel {
  String bin;
  String verifiedDate;
  String itemCode;
  String legacyItem;
  String unitPerCase;
  String verifiedQTY;
  String pickQTY;
  String action;
  String cycleCountID;
  String verifiedBy;
  String lpn;
  String warehouse;
  String bpn;


  CycleCountV2BulkListModel({
    required this.pickQTY,
    required this.itemCode,
    required this.legacyItem,
    required this.action,
    required this.cycleCountID,
    required this.unitPerCase,
    required this.verifiedQTY,
    required this.bin,
    required this.verifiedDate,
    required this.verifiedBy,
    required this.lpn,
    required this.warehouse,
    required this.bpn,
  });

  factory CycleCountV2BulkListModel.fromJson(List<dynamic> json) {
    return CycleCountV2BulkListModel(
      itemCode: json[1]?.toString() ?? '',
      legacyItem: json[14]?.toString() ?? '',
      bin: json[8]?.toString() ?? '',
      verifiedDate: json[3]?.toString() ?? '',
      unitPerCase: json[29]?.toString() ?? '',
      verifiedQTY: json[30]?.toString() ?? '',
      pickQTY: json[31]?.toString() ?? '',
      action: json[4]?.toString() ?? '',
      cycleCountID: json[32]?.toString() ?? '',
      verifiedBy: json[6]?.toString() ?? '',
      lpn: json[6]?.toString() ?? '',
      warehouse: json[6]?.toString() ?? '',
      bpn: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pickQTY'] = pickQTY;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['action'] = action;
    data['cycleCountID'] = cycleCountID;
    data['unitPerCase'] = unitPerCase;
    data['verifiedQTY'] = verifiedQTY;
    data['bin'] = bin;
    data['verifiedDate'] = verifiedDate;
    data['lpn'] = lpn;
    data['warehouse'] = warehouse;
    data['bpn'] = bpn;
    data['verifiedBy'] = verifiedBy;
    return data;
  }
}
