///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ShippingQuoteListModel {
  String boxCount;
  String totalPalletCount;
  String palletCount;
  String totalWeight;
  String classes;
  String nmfc;
  String overWeight;
  String tlOverWeight;
  String totalCF;
  String pcf;

  ShippingQuoteListModel({
    required this.totalPalletCount,
    required this.palletCount,
    required this.nmfc,
    required this.boxCount,
    required this.classes,
    required this.totalWeight,
    required this.overWeight,
    required this.tlOverWeight,
    required this.totalCF,
    required this.pcf,
  });

  factory ShippingQuoteListModel.fromJson(List<dynamic> json) {
    return ShippingQuoteListModel(
      totalPalletCount: json[1]?.toString() ?? '',
      palletCount: json[2]?.toString() ?? '',
      nmfc: json[10]?.toString() ?? '',
      boxCount: json[10]?.toString() ?? '',
      classes: json[10]?.toString() ?? '',
      totalWeight: json[10]?.toString() ?? '',
      overWeight: json[10]?.toString() ?? '',
      tlOverWeight: json[10]?.toString() ?? '',
      totalCF: json[10]?.toString() ?? '',
      pcf: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['totalPalletCount'] = totalPalletCount;
    data['palletCount'] = palletCount;
    data['nmfc'] = nmfc;
    data['boxCount'] = boxCount;
    data['classes'] = classes;
    data['totalWeight'] = totalWeight;
    data['overWeight'] = overWeight;
    data['tlOverWeight'] = tlOverWeight;
    data['totalCF'] = totalCF;
    data['pcf'] = pcf;
    return data;
  }
}
