///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ShippingQuoteListDetailModel {
  String quantity;
  String qtyOnHand;
  String warehouse;
  String itemCode;
  String legacyItem;
  String description;
  String totalCaseCount;
  String ti;
  String hi;
  String pltCount;
  String max;
  String qtyCase;
  String weightCase;
  String weightType;
  String totalWeight;

  ShippingQuoteListDetailModel({
    required this.qtyOnHand,
    required this.warehouse,
    required this.description,
    required this.quantity,
    required this.legacyItem,
    required this.itemCode,
    required this.totalCaseCount,
    required this.ti,
    required this.hi,
    required this.pltCount,
    required this.max,
    required this.qtyCase,
    required this.weightCase,
    required this.weightType,
    required this.totalWeight,
  });

  factory ShippingQuoteListDetailModel.fromJson(List<dynamic> json) {
    return ShippingQuoteListDetailModel(
      qtyOnHand: json[1]?.toString() ?? '',
      warehouse: json[2]?.toString() ?? '',
      description: json[10]?.toString() ?? '',
      quantity: json[10]?.toString() ?? '',
      legacyItem: json[10]?.toString() ?? '',
      itemCode: json[10]?.toString() ?? '',
      totalCaseCount: json[10]?.toString() ?? '',
      ti: json[10]?.toString() ?? '',
      hi: json[10]?.toString() ?? '',
      pltCount: json[10]?.toString() ?? '',
      max: json[10]?.toString() ?? '',
      qtyCase: json[10]?.toString() ?? '',
      weightCase: json[10]?.toString() ?? '',
      weightType: json[10]?.toString() ?? '',
      totalWeight: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['qtyOnHand'] = qtyOnHand;
    data['warehouse'] = warehouse;
    data['description'] = description;
    data['quantity'] = quantity;
    data['legacyItem'] = legacyItem;
    data['itemCode'] = itemCode;
    data['totalCaseCount'] = totalCaseCount;
    data['ti'] = ti;
    data['hi'] = hi;
    data['pltCount'] = pltCount;
    data['max'] = max;
    data['qtyCase'] = qtyCase;
    data['weightType'] = weightType;
    data['weightCase'] = weightCase;
    data['totalWeight'] = totalWeight;
    return data;
  }
}
