///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AuditHistoryModel {
  String order;
  String pickUpDateAppointment;
  String auditStartDate;
  String orderType;
  String auditEndDate;
  String auditEndBy;
  String fulFillmentDate;
  String fulFillmentBy;
  String auditStartedBy;
  String duration;
  String totalQty;
  String shipState;
  String orderStatus;
  String customerName;
  String shipVia;
  String shipDate;
  String loc;
  String auditResult;


  AuditHistoryModel({
    required this.pickUpDateAppointment,
    required this.order,
    required this.auditStartDate,
    required this.orderType,
    required this.auditEndDate,
    required this.auditEndBy,
    required this.fulFillmentDate,
    required this.fulFillmentBy,
    required this.auditStartedBy,
    required this.duration,
    required this.totalQty,
    required this.shipState,
    required this.orderStatus,
    required this.customerName,
    required this.shipVia,
    required this.shipDate,
    required this.loc,
    required this.auditResult,
  });

  factory AuditHistoryModel.fromJson(List<dynamic> json) {
    return AuditHistoryModel(
      order: json[1]?.toString() ?? '',
      orderType: json[2]?.toString() ?? '',
      pickUpDateAppointment: json[3]?.toString() ?? '',
      auditEndDate: json[14]?.toString() ?? '',
      auditEndBy: json[6]?.toString() ?? '',
      fulFillmentDate: json[5]?.toString() ?? '',
      fulFillmentBy: json[7]?.toString() ?? '',
      auditStartDate: json[8]?.toString() ?? '',
      auditStartedBy: json[11]?.toString() ?? '',
      duration: json[10]?.toString() ?? '',
      totalQty: json[10]?.toString() ?? '',
      shipState: json[10]?.toString() ?? '',
      orderStatus: json[10]?.toString() ?? '',
      customerName: json[10]?.toString() ?? '',
      shipVia: json[10]?.toString() ?? '',
      shipDate: json[10]?.toString() ?? '',
      loc: json[10]?.toString() ?? '',
      auditResult: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pickUpDateAppointment'] = pickUpDateAppointment;
    data['order'] = order;
    data['auditStartDate'] = auditStartDate;
    data['orderType'] = orderType;
    data['auditEndDate'] = auditEndDate;
    data['auditEndBy'] = auditEndBy;
    data['fulFillmentDate'] = fulFillmentDate;
    data['fulFillmentBy'] = fulFillmentBy;
    data['auditStartedBy'] = auditStartedBy;
    data['duration'] = duration;
    data['totalQty'] = totalQty;
    data['shipState'] = shipState;
    data['orderStatus'] = orderStatus;
    data['customerName'] = customerName;
    data['shipVia'] = shipVia;
    data['shipDate'] = shipDate;
    data['loc'] = loc;
    data['auditResult'] = auditResult;
    return data;
  }
}
