///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StagedPalletsModel {
  String wareHouse;
  String po;
  String truckBin;
  String palletID;
  String loadedDate;
  String stagedUser;
  String stagedDate;
  String stagedBin;
  String loadedBy;
  String appointTime;
  String shipVia;
  String customer;
  String priority;
  String assignLoader;
  String status;
  String soCode;
  String route;
  String dock;


  StagedPalletsModel({
    required this.po,
    required this.wareHouse,
    required this.truckBin,
    required this.palletID,
    required this.loadedDate,
    required this.stagedUser,
    required this.stagedDate,
    required this.stagedBin,
    required this.loadedBy,
    required this.appointTime,
    required this.shipVia,
    required this.customer,
    required this.priority,
    required this.assignLoader,
    required this.status,
    required this.soCode,
    required this.route,
    required this.dock,
  });

  factory StagedPalletsModel.fromJson(List<dynamic> json) {
    return StagedPalletsModel(
      soCode: json[0]?.toString() ?? '',
      wareHouse: json[1]?.toString() ?? '',
      po: json[23]?.toString() ?? '',
      palletID: json[2]?.toString() ?? '',
      loadedDate: json[6]?.toString() ?? '',
      stagedUser: json[14]?.toString() ?? '',
      stagedDate: json[15]?.toString() ?? '',
      truckBin: json[8]?.toString() ?? '',
      stagedBin: json[12]?.toString() ?? '',
      loadedBy: json[10]?.toString() ?? '',
      appointTime: json[10]?.toString() ?? '',
      shipVia: json[18]?.toString() ?? '',
      customer: json[24]?.toString() ?? '',
      priority: json[10]?.toString() ?? '',
      assignLoader: json[10]?.toString() ?? '',
      status: json[3]?.toString() ?? '',
      route: json[10]?.toString() ?? '',
      dock: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['po'] = po;
    data['wareHouse'] = wareHouse;
    data['truckBin'] = truckBin;
    data['palletID'] = palletID;
    data['loadedDate'] = loadedDate;
    data['stagedUser'] = stagedUser;
    data['stagedDate'] = stagedDate;
    data['stagedBin'] = stagedBin;
    data['loadedBy'] = loadedBy;
    data['appointTime'] = appointTime;
    data['shipVia'] = shipVia;
    data['customer'] = customer;
    data['priority'] = priority;
    data['assignLoader'] = assignLoader;
    data['status'] = status;
    data['soCode'] = soCode;
    data['route'] = route;
    data['dock'] = dock;
    return data;
  }
}
