///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BPTOSLogSummaryModel {
  String availableQuantity;
  String warehouse;
  String detail;
  String itemCode;
  String legacyItem;
  String totalQty;
  String onHandQty;
  String etaWarehouse;
  String totalTOS;

  BPTOSLogSummaryModel({
    required this.itemCode,
    required this.etaWarehouse,
    required this.onHandQty,
    required this.availableQuantity,
    required this.legacyItem,
    required this.warehouse,
    required this.totalQty,
    required this.totalTOS,
    required this.detail,
  });

  factory BPTOSLogSummaryModel.fromJson(List<dynamic> json) {
    return BPTOSLogSummaryModel(
      warehouse: json[28]?.toString() ?? '',
      itemCode: json[14]?.toString() ?? '',
      etaWarehouse: json[6]?.toString() ?? '',
      onHandQty: json[12]?.toString() ?? '',
      availableQuantity: json[26]?.toString() ?? '',
      legacyItem: json[3]?.toString() ?? '',
      totalQty: json[18]?.toString() ?? '',
      totalTOS: json[3]?.toString() ?? '',
      detail: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itemCode'] = itemCode;
    data['etaWarehouse'] = etaWarehouse;
    data['onHandQty'] = onHandQty;
    data['availableQuantity'] = availableQuantity;
    data['legacyItem'] = legacyItem;
    data['warehouse'] = warehouse;
    data['totalQty'] = totalQty;
    data['totalTOS'] = totalTOS;
    data['detail'] = detail;
    return data;
  }
}
