///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BPNHistoryExpansionModel {
  String warehouse;
  String lpn;
  String bin;
  String itemCode;
  String legacyItem;
  String currentQty;
  String description;


  BPNHistoryExpansionModel({
    required this.bin,
    required this.lpn,
    required this.currentQty,
    required this.itemCode,
    required this.description,
    required this.warehouse,
    required this.legacyItem,
  });

  factory BPNHistoryExpansionModel.fromJson(List<dynamic> json) {
    return BPNHistoryExpansionModel(
      warehouse: json[28]?.toString() ?? '',
      bin: json[14]?.toString() ?? '',
      lpn: json[8]?.toString() ?? '',
      currentQty: json[26]?.toString() ?? '',
      itemCode: json[23]?.toString() ?? '',
      description: json[3]?.toString() ?? '',
      legacyItem: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['lpn'] = lpn;
    data['currentQty'] = currentQty;
    data['itemCode'] = itemCode;
    data['description'] = description;
    data['warehouse'] = warehouse;
    data['legacyItem'] = legacyItem;
    return data;
  }
}
