///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SPPackingShipmentBypassModel {
  String po;
  String salesOrd;
  String kpPage;
  String customerName;
  String warehouse;
  String shipZipCode;
  String carrier;
  String boxType;
  String trackNo;
  String rate;
  String fulfillmentDate;
  String packStartBy;
  String packStartDate;
  String weight;
  String fulfillmentBy;
  String shipToAddress;
  String orderStatus;

  SPPackingShipmentBypassModel({
    required this.weight,
    required this.shipZipCode,
    required this.trackNo,
    required this.fulfillmentDate,
    required this.packStartBy,
    required this.packStartDate,
    required this.rate,
    required this.po,
    required this.carrier,
    required this.salesOrd,
    required this.boxType,
    required this.fulfillmentBy,
    required this.shipToAddress,
    required this.orderStatus,
    required this.warehouse,
    required this.customerName,
    required this.kpPage,
  });

  factory SPPackingShipmentBypassModel.fromJson(List<dynamic> json) {
    return SPPackingShipmentBypassModel(
      salesOrd: json[28]?.toString() ?? '',
      weight: json[4]?.toString() ?? '',
      shipZipCode: json[14]?.toString() ?? '',
      trackNo: json[0]?.toString() ?? '',
      fulfillmentDate: json[15]?.toString() ?? '',
      packStartBy: json[7]?.toString() ?? '',
      packStartDate: json[8]?.toString() ?? '',
      rate: json[12]?.toString() ?? '',
      po: json[26]?.toString() ?? '',
      carrier: json[3]?.toString() ?? '',
      boxType: json[18]?.toString() ?? '',
      fulfillmentBy: json[23]?.toString() ?? '',
      shipToAddress: json[3]?.toString() ?? '',
      orderStatus: json[18]?.toString() ?? '',
      warehouse: json[18]?.toString() ?? '',
      customerName: json[18]?.toString() ?? '',
      kpPage: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['weight'] = weight;
    data['shipZipCode'] = shipZipCode;
    data['trackNo'] = trackNo;
    data['fulfillmentDate'] = fulfillmentDate;
    data['packStartBy'] = packStartBy;
    data['packStartDate'] = packStartDate;
    data['rate'] = rate;
    data['po'] = po;
    data['carrier'] = carrier;
    data['salesOrd'] = salesOrd;
    data['boxType'] = boxType;
    data['fulfillmentBy'] = fulfillmentBy;
    data['shipToAddress'] = shipToAddress;
    data['orderStatus'] = orderStatus;
    data['warehouse'] = warehouse;
    data['customerName'] = customerName;
    data['kpPage'] = kpPage;
    return data;
  }
}
