///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PurolatorCloseoutModel {
  String salesOrd;
  String customerName;
  String warehouse;
  String carrier;
  String boxType;
  String trackNo;
  String weight;
  String shipToAddress;

  PurolatorCloseoutModel({
    required this.weight,
    required this.trackNo,
    required this.carrier,
    required this.salesOrd,
    required this.boxType,
    required this.shipToAddress,
    required this.warehouse,
    required this.customerName,
  });

  factory PurolatorCloseoutModel.fromJson(List<dynamic> json) {
    return PurolatorCloseoutModel(
      salesOrd: json[28]?.toString() ?? '',
      weight: json[4]?.toString() ?? '',
      trackNo: json[0]?.toString() ?? '',
      carrier: json[3]?.toString() ?? '',
      boxType: json[18]?.toString() ?? '',
      warehouse: json[18]?.toString() ?? '',
      customerName: json[18]?.toString() ?? '',
      shipToAddress: json[3]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['weight'] = weight;
    data['trackNo'] = trackNo;
    data['carrier'] = carrier;
    data['salesOrd'] = salesOrd;
    data['boxType'] = boxType;
    data['shipToAddress'] = shipToAddress;
    data['warehouse'] = warehouse;
    data['customerName'] = customerName;
    return data;
  }
}
