///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PlaceHolderListModel {
  String php;
  String bin;
  String warehouse;
  String createData;
  String createBy;
  String shipDate;
  String shipBy;
  String action;
  String po;

  PlaceHolderListModel({
    required this.bin,
    required this.warehouse,
    required this.shipDate,
    required this.action,
    required this.php,
    required this.po,
    required this.shipBy,
    required this.createBy,
    required this.createData,
  });

  factory PlaceHolderListModel.fromJson(List<dynamic> json) {
    return PlaceHolderListModel(
      bin: json[1]?.toString() ?? '',
      warehouse: json[2]?.toString() ?? '',
      shipDate: json[10]?.toString() ?? '',
      action: json[10]?.toString() ?? '',
      php: json[10]?.toString() ?? '',
      po: json[10]?.toString() ?? '',
      shipBy: json[10]?.toString() ?? '',
      createBy: json[10]?.toString() ?? '',
      createData: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['warehouse'] = warehouse;
    data['shipDate'] = shipDate;
    data['action'] = action;
    data['php'] = php;
    data['po'] = po;
    data['shipBy'] = shipBy;
    data['createBy'] = createBy;
    data['createData'] = createData;
    return data;
  }
}
