///
/// Code generated by jsonwarehouseDartModel https://ashamp.github.io/jsonwarehouseDartModel/
///
class DispatchModel {
  String warehouse;
  String city;
  String state;
  String so;
  String orderType;
  String customer;
  String confirmedAppt;
  String totalWeight;
  String shipDate;
  String receivingHours;
  String status;
  String shipMethod;
  String category;
  String zip;
  String appt;
  String address;
  String boxCount;
  String palletCount;
  String hours;
  String pickedBy;
  String checkedBy;
  String companyBusinessName;
  String contactPerson;
  String phone;
  String zone;
  String trailerAccess;
  String loadingDock;
  String liftGate;
  String limitedAccess;
  String approveDate;
  String approveBy;
  String approveNotes;
  String bolPrinted;
  String palletExchange;
  String lumper;

  DispatchModel({
    required this.zip,
    required this.city,
    required this.palletCount,
    required this.state,
    required this.pickedBy,
    required this.shipMethod,
    required this.hours,
    required this.boxCount,
    required this.confirmedAppt,
    required this.status,
    required this.shipDate,
    required this.address,
    required this.warehouse,
    required this.appt,
    required this.category,
    required this.receivingHours,
    required this.totalWeight,
    required this.customer,
    required this.so,
    required this.orderType,
    required this.loadingDock,
    required this.palletExchange,
    required this.approveNotes,
    required this.companyBusinessName,
    required this.trailerAccess,
    required this.phone,
    required this.approveBy,
    required this.approveDate,
    required this.liftGate,
    required this.zone,
    required this.contactPerson,
    required this.checkedBy,
    required this.lumper,
    required this.bolPrinted,
    required this.limitedAccess,
  });

  factory DispatchModel.fromJson(List<dynamic> json) {
    return DispatchModel(
      city: json[1]?.toString() ?? '',
      state: json[2]?.toString() ?? '',
      zip: json[3]?.toString() ?? '',
      pickedBy: json[6]?.toString() ?? '',
      shipMethod: json[5]?.toString() ?? '',
      hours: json[7]?.toString() ?? '',
      palletCount: json[8]?.toString() ?? '',
      boxCount: json[10]?.toString() ?? '',
      confirmedAppt: json[10]?.toString() ?? '',
      status: json[10]?.toString() ?? '',
      shipDate: json[10]?.toString() ?? '',
      address: json[10]?.toString() ?? '',
      warehouse: json[10]?.toString() ?? '',
      category: json[10]?.toString() ?? '',
      appt: json[10]?.toString() ?? '',
      receivingHours: json[10]?.toString() ?? '',
      totalWeight: json[10]?.toString() ?? '',
      customer: json[10]?.toString() ?? '',
      so: json[10]?.toString() ?? '',
      orderType: json[10]?.toString() ?? '',
      palletExchange: json[7]?.toString() ?? '',
      bolPrinted: json[8]?.toString() ?? '',
      approveNotes: json[10]?.toString() ?? '',
      companyBusinessName: json[10]?.toString() ?? '',
      trailerAccess: json[10]?.toString() ?? '',
      phone: json[10]?.toString() ?? '',
      approveBy: json[10]?.toString() ?? '',
      lumper: json[10]?.toString() ?? '',
      liftGate: json[10]?.toString() ?? '',
      approveDate: json[10]?.toString() ?? '',
      zone: json[10]?.toString() ?? '',
      contactPerson: json[10]?.toString() ?? '',
      checkedBy: json[10]?.toString() ?? '',
      loadingDock: json[10]?.toString() ?? '',
      limitedAccess: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['zip'] = zip;
    data['city'] = city;
    data['palletCount'] = palletCount;
    data['state'] = state;
    data['pickedBy'] = pickedBy;
    data['shipMethod'] = shipMethod;
    data['hours'] = hours;
    data['boxCount'] = boxCount;
    data['confirmedAppt'] = confirmedAppt;
    data['status'] = status;
    data['shipDate'] = shipDate;
    data['address'] = address;
    data['warehouse'] = warehouse;
    data['appt'] = appt;
    data['category'] = category;
    data['receivingHours'] = receivingHours;
    data['totalWeight'] = totalWeight;
    data['customer'] = customer;
    data['so'] = so;
    data['orderType'] = orderType;
    data['loadingDock'] = loadingDock;
    data['palletExchange'] = palletExchange;
    data['approveNotes'] = approveNotes;
    data['companyBusinessName'] = companyBusinessName;
    data['trailerAccess'] = trailerAccess;
    data['phone'] = phone;
    data['approveBy'] = approveBy;
    data['bolPrinted'] = bolPrinted;
    data['approveDate'] = approveDate;
    data['liftGate'] = liftGate;
    data['zone'] = zone;
    data['contactPerson'] = contactPerson;
    data['checkedBy'] = checkedBy;
    data['lumper'] = lumper;
    data['limitedAccess'] = limitedAccess;
    return data;
  }
}
