///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NSAdjustmentHistoryModel {
  String adjustmentID;
  String warehouse;
  String itemCode;
  String legacyItem;
  String internalID;
  String itemType;
  String description;

  String nsQTY;
  String kpQTY;
  String pickQTY;
  String countQTY;
  String qtyDiff;
  String qtyDiff2;

  String avgCost;
  String amtDiff;
  String createDate;
  String createdBy;
  String nsIA;
  String adjustmentDate;
  String adjustmentBy;

  NSAdjustmentHistoryModel({
    required this.itemType,
    required this.description,
    required this.createdBy,
    required this.pickQTY,
    required this.amtDiff,
    required this.qtyDiff,
    required this.qtyDiff2,
    required this.avgCost,
    required this.warehouse,
    required this.nsIA,
    required this.adjustmentDate,
    required this.itemCode,
    required this.legacyItem,
    required this.createDate,
    required this.countQTY,
    required this.adjustmentID,
    required this.internalID,
    required this.kpQTY,
    required this.nsQTY,
    required this.adjustmentBy,
  });

  factory NSAdjustmentHistoryModel.fromJson(List<dynamic> json) {
    return NSAdjustmentHistoryModel(
      warehouse: json[28]?.toString() ?? '',
      description: json[28]?.toString() ?? '',
      itemType: json[14]?.toString() ?? '',
      createdBy: json[8]?.toString() ?? '',
      pickQTY: json[26]?.toString() ?? '',
      amtDiff: json[23]?.toString() ?? '',
      qtyDiff: json[3]?.toString() ?? '',
      qtyDiff2: json[3]?.toString() ?? '',
      avgCost: json[3]?.toString() ?? '',
      nsIA: json[18]?.toString() ?? '',
      adjustmentDate: json[18]?.toString() ?? '',
      itemCode: json[18]?.toString() ?? '',
      legacyItem: json[18]?.toString() ?? '',
      createDate: json[18]?.toString() ?? '',
      countQTY: json[18]?.toString() ?? '',
      adjustmentID: json[18]?.toString() ?? '',
      internalID: json[18]?.toString() ?? '',
      kpQTY: json[18]?.toString() ?? '',
      nsQTY: json[18]?.toString() ?? '',
      adjustmentBy: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itemType'] = itemType;
    data['description'] = description;
    data['createdBy'] = createdBy;
    data['pickQTY'] = pickQTY;
    data['amtDiff'] = amtDiff;
    data['qtyDiff'] = qtyDiff;
    data['qtyDiff2'] = qtyDiff2;
    data['avgCost'] = avgCost;
    data['warehouse'] = warehouse;
    data['nsIA'] = nsIA;
    data['adjustmentDate'] = adjustmentDate;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['createDate'] = createDate;
    data['countQTY'] = countQTY;
    data['adjustmentID'] = adjustmentID;
    data['internalID'] = internalID;
    data['nsQTY'] = nsQTY;
    data['kpQTY'] = kpQTY;
    data['adjustmentBy'] = adjustmentBy;
    return data;
  }
}
