///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BulkPlateNumberHistoryModel {
  String override;
  String user;
  String date;


  BulkPlateNumberHistoryModel({
    required this.user,
    required this.override,
    required this.date,
  });

  factory BulkPlateNumberHistoryModel.fromJson(List<dynamic> json) {
    return BulkPlateNumberHistoryModel(
      override: json[4]?.toString() ?? '',
      user: json[6]?.toString() ?? '',
      date: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['override'] = override;
    data['user'] = user;
    data['date'] = date;
    return data;
  }
}