///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpsQuoteModel {
  String warehouse;
  String action;
  String palletMovementDate;
  String item;
  String so;
  String qty;
  String legacy;
  String quantity;

  UpsQuoteModel({
    required this.palletMovementDate,
    required this.action,
    required this.so,
    required this.qty,
    required this.warehouse,
    required this.item,
    required this.legacy,
    required this.quantity,
  });

  factory UpsQuoteModel.fromJson(List<dynamic> json) {
    return UpsQuoteModel(
      warehouse: json[28]?.toString() ?? '',
      action: json[28]?.toString() ?? '',
      palletMovementDate: json[14]?.toString() ?? '',
      so: json[23]?.toString() ?? '',
      qty: json[3]?.toString() ?? '',
      item: json[18]?.toString() ?? '',
      legacy: json[18]?.toString() ?? '',
      quantity: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['palletMovementDate'] = palletMovementDate;
    data['so'] = so;
    data['qty'] = qty;
    data['warehouse'] = warehouse;
    data['item'] = item;
    data['legacy'] = legacy;
    data['quantity'] = quantity;
    return data;
  }
}
