///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BPNAuditModel {
  String pickBin;
  String fullPallet;
  String origin;
  String itemCode;
  String legacyItem;
  String onHandQty;
  String kpiPar;
  String ordQty;
  String boxQty;
  String pcsQty;
  String filledQty;
  String balance;
  String pickTime;
  String lpnTotal;
  String description;
  String weight;
  String whNotes;
  String location;

  BPNAuditModel({
    required this.pickBin,
    required this.fullPallet,
    required this.origin,
    required this.itemCode,
    required this.legacyItem,
    required this.onHandQty,
    required this.kpiPar,
    required this.ordQty,
    required this.boxQty,
    required this.pcsQty,
    required this.filledQty,
    required this.balance,
    required this.pickTime,
    required this.lpnTotal,
    required this.description,
    required this.weight,
    required this.whNotes,
    required this.location,
  });

  factory BPNAuditModel.fromJson(List<dynamic> json) {
    return BPNAuditModel(
      pickBin: json[1]?.toString() ?? '',
      fullPallet: json[42]?.toString() ?? '',
      origin: json[0]?.toString() ?? '',
      itemCode: json[2]?.toString() ?? '',
      legacyItem: json[22]?.toString() ?? '',
      onHandQty: json[29]?.toString() ?? '',
      kpiPar: json[0]?.toString() ?? '',
      ordQty: json[37]?.toString() ?? '',
      boxQty: json[10]?.toString() ?? '',
      pcsQty: json[11]?.toString() ?? '',
      filledQty: json[11]?.toString() ?? '',
      balance: json[4]?.toString() ?? '',
      pickTime: '00:00',
      lpnTotal: json[23]?.toString() ?? '',
      description: json[7]?.toString() ?? '',
      weight: json[28]?.toString() ?? '',
      whNotes: json[28]?.toString() ?? '',
      location: json[33]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pickBin'] = pickBin;
    data['fullPallet'] = fullPallet;
    data['origin'] = origin;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['onHandQty'] = onHandQty;
    data['kpiPar'] = kpiPar;
    data['ordQty'] = ordQty;
    data['boxQty'] = boxQty;
    data['pcsQty'] = pcsQty;
    data['filledQty'] = filledQty;
    data['balance'] = balance;
    data['pickTime'] = pickTime;
    data['lpnTotal'] = lpnTotal;
    data['description'] = description;
    data['weight'] = weight;
    data['whNotes'] = whNotes;
    data['location'] = location;
    return data;
  }
}
