///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BinCountSummaryModel {
  String internalID;
  String description;
  String kpQty;
  String itemCode;
  String legacyItem;
  String sysDiff;
  String sysDiff2;
  String cntQty;
  String dpnQty;
  String unknownReturns;
  String pickQty;
  String receivedQty;
  String ccID;
  String sysDiffAvgCost;
  String nsOHQty;
  String qtyDiff;
  String qtyDiff2;
  String avgCost;
  String amtDiff;
  String lastSyncDate;


  BinCountSummaryModel({
    required this.sysDiffAvgCost,
    required this.itemCode,
    required this.legacyItem,
    required this.cntQty,
    required this.unknownReturns,
    required this.pickQty,
    required this.receivedQty,
    required this.ccID,
    required this.dpnQty,
    required this.kpQty,
    required this.description,
    required this.sysDiff,
    required this.sysDiff2,
    required this.internalID,
    required this.nsOHQty,
    required this.qtyDiff,
    required this.qtyDiff2,
    required this.avgCost,
    required this.amtDiff,
    required this.lastSyncDate,
  });

  factory BinCountSummaryModel.fromJson(List<dynamic> json) {
    return BinCountSummaryModel(
      itemCode: json[1]?.toString() ?? '',
      legacyItem: json[14]?.toString() ?? '',
      internalID: json[8]?.toString() ?? '',
      ccID: json[25]?.toString() ?? '',
      description: json[2]?.toString() ?? '',
      nsOHQty: json[3]?.toString() ?? '',
      kpQty: json[11]?.toString() ?? '',
      sysDiff: json[29]?.toString() ?? '',
      sysDiff2: json[30]?.toString() ?? '',
      sysDiffAvgCost: json[31]?.toString() ?? '',
      cntQty: json[4]?.toString() ?? '',
      dpnQty: json[32]?.toString() ?? '',
      unknownReturns: json[38]?.toString() ?? '',
      pickQty: json[18]?.toString() ?? '',
      receivedQty: json[33]?.toString() ?? '',
      qtyDiff: json[5]?.toString() ?? '',
      qtyDiff2: json[6]?.toString() ?? '',
      avgCost: json[9]?.toString() ?? '',
      amtDiff: json[7]?.toString() ?? '',
      lastSyncDate: json[12]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sysDiffAvgCost'] = sysDiffAvgCost;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['cntQty'] = cntQty;
    data['unknownReturns'] = unknownReturns;
    data['pickQty'] = pickQty;
    data['receivedQty'] = receivedQty;
    data['ccID'] = ccID;
    data['dpnQty'] = dpnQty;
    data['kpQty'] = kpQty;
    data['description'] = description;
    data['sysDiff'] = sysDiff;
    data['sysDiff2'] = sysDiff2;
    data['internalID'] = internalID;
    data['nsOHQty'] = nsOHQty;
    data['qtyDiff'] = qtyDiff;
    data['qtyDiff2'] = qtyDiff2;
    data['avgCost'] = avgCost;
    data['amtDiff'] = amtDiff;
    data['lastSyncDate'] = lastSyncDate;
    return data;
  }
}
