///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BinCountSummaryExpansionModel {
  String license;
  String bin;
  String quantity;
  String cycleCountID;
  String addedBy;
  String addedDate;


  BinCountSummaryExpansionModel({
    required this.license,
    required this.bin,
    required this.quantity,
    required this.cycleCountID,
    required this.addedBy,
    required this.addedDate,
  });

  factory BinCountSummaryExpansionModel.fromJson(List<dynamic> json) {
    return BinCountSummaryExpansionModel(
      license: json[0]?.toString() ?? '',
      bin: json[1]?.toString() ?? '',
      quantity: json[2]?.toString() ?? '',
      cycleCountID: json[7]?.toString() ?? '',
      addedBy: json[4]?.toString() ?? '',
      addedDate: json[5]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['license'] = license;
    data['bin'] = bin;
    data['quantity'] = quantity;
    data['cycleCountID'] = cycleCountID;
    data['addedBy'] = addedBy;
    data['addedDate'] = addedDate;
    return data;
  }
}
