///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SoCubicFeetListModel {
  String qty;
  String itemCode;
  String legacyItem;
  String description;
  String totalCubicFeet;
  String cubicFeet;
  String itemCubicFeet;
  String grossWeight;
  String itemWeight;
  String totalWeight;

  SoCubicFeetListModel({
    required this.description,
    required this.qty,
    required this.legacyItem,
    required this.itemCode,
    required this.totalCubicFeet,
    required this.cubicFeet,
    required this.itemCubicFeet,
    required this.grossWeight,
    required this.itemWeight,
    required this.totalWeight,
  });

  factory SoCubicFeetListModel.fromJson(List<dynamic> json) {
    return SoCubicFeetListModel(
      description: json[10]?.toString() ?? '',
      qty: json[10]?.toString() ?? '',
      legacyItem: json[10]?.toString() ?? '',
      itemCode: json[10]?.toString() ?? '',
      totalCubicFeet: json[10]?.toString() ?? '',
      cubicFeet: json[10]?.toString() ?? '',
      itemCubicFeet: json[10]?.toString() ?? '',
      grossWeight: json[10]?.toString() ?? '',
      itemWeight: json[10]?.toString() ?? '',
      totalWeight: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['description'] = description;
    data['qty'] = qty;
    data['legacyItem'] = legacyItem;
    data['itemCode'] = itemCode;
    data['totalCubicFeet'] = totalCubicFeet;
    data['cubicFeet'] = cubicFeet;
    data['itemCubicFeet'] = itemCubicFeet;
    data['grossWeight'] = grossWeight;
    data['itemWeight'] = itemWeight;
    data['totalWeight'] = totalWeight;
    return data;
  }
}
