///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SOPickDurationModel {
  String warehouse;
  String userName;
  String totalSO;
  String durationAverage;
  String itemAverage;


  SOPickDurationModel({
    required this.userName,
    required this.totalSO,
    required this.warehouse,
    required this.durationAverage,
    required this.itemAverage,
  });

  factory SOPickDurationModel.fromJson(List<dynamic> json) {
    return SOPickDurationModel(
      userName: json[11]?.toString() ?? '',
      totalSO: json[3]?.toString() ?? '',
      warehouse: json[10]?.toString() ?? '',
      durationAverage: json[2]?.toString() ?? '',
      itemAverage: json[8]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userName'] = userName;
    data['totalSO'] = totalSO;
    data['warehouse'] = warehouse;
    data['durationAverage'] = durationAverage;
    data['itemAverage'] = itemAverage;
    return data;
  }
}
