///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CycleCountReviewModel {
  String lpn;
  String bin;
  String originalQty;
  String itemCode;
  String legacyItem;
  String verifiedBy;
  String verifiedQty;
  String verifiedDate;
  String createdBy;
  String createdDate;
  String currentQty;
  String cycleCountID;
  String source;


  CycleCountReviewModel({
    required this.verifiedDate,
    required this.itemCode,
    required this.legacyItem,
    required this.createdBy,
    required this.createdDate,
    required this.originalQty,
    required this.verifiedBy,
    required this.verifiedQty,
    required this.lpn,
    required this.bin,
    required this.currentQty,
    required this.cycleCountID,
    required this.source,
  });

  factory CycleCountReviewModel.fromJson(List<dynamic> json) {
    return CycleCountReviewModel(
      itemCode: json[1]?.toString() ?? '',
      legacyItem: json[14]?.toString() ?? '',
      lpn: json[8]?.toString() ?? '',
      bin: json[3]?.toString() ?? '',
      originalQty: json[11]?.toString() ?? '',
      verifiedBy: json[29]?.toString() ?? '',
      verifiedQty: json[30]?.toString() ?? '',
      verifiedDate: json[31]?.toString() ?? '',
      createdBy: json[4]?.toString() ?? '',
      createdDate: json[32]?.toString() ?? '',
      currentQty: json[6]?.toString() ?? '',
      cycleCountID: json[6]?.toString() ?? '',
      source: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['verifiedDate'] = verifiedDate;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['createdBy'] = createdBy;
    data['createdDate'] = createdDate;
    data['originalQty'] = originalQty;
    data['verifiedBy'] = verifiedBy;
    data['verifiedQty'] = verifiedQty;
    data['lpn'] = lpn;
    data['bin'] = bin;
    data['cycleCountID'] = cycleCountID;
    data['source'] = source;
    return data;
  }
}
