///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DockLoadingPhotoModel {
  String action;
  String fileName;
  String memo;
  String addedBy;
  String addedDate;

  DockLoadingPhotoModel({
    required this.action,
    required this.fileName,
    required this.memo,
    required this.addedBy,
    required this.addedDate,
  });

  factory DockLoadingPhotoModel.fromJson(List<dynamic> json) {
    return DockLoadingPhotoModel(
      action: json[1]?.toString() ?? '',
      fileName: json[1]?.toString() ?? '',
      memo: json[0]?.toString() ?? '',
      addedBy: json[0]?.toString() ?? '',
      addedDate: json[0]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['fileName'] = fileName;
    data['memo'] = memo;
    data['addedBy'] = addedBy;
    data['addedDate'] = addedDate;
    return data;
  }
}
