///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DockLoadingLoadOverrideModel {
  String date;
  String override;
  String user;

  DockLoadingLoadOverrideModel({
    required this.date,
    required this.override,
    required this.user,
  });

  factory DockLoadingLoadOverrideModel.fromJson(List<dynamic> json) {
    return DockLoadingLoadOverrideModel(
      date: json[1]?.toString() ?? '',
      override: json[1]?.toString() ?? '',
      user: json[0]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['override'] = override;
    data['user'] = user;
    return data;
  }
}
