///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DockLoadingPalletsModel {
  String soCode;
  String palletID;
  String zone;
  String spot;
  String weight;
  String truckBin;
  String loadedDate;
  String loadType;
  String warehouse;
  String loadedBy;
  String stagedDate;
  String stagedBin;
  String quantity;
  String legacyItem;
  String itemCode;

  DockLoadingPalletsModel({
    required this.soCode,
    required this.palletID,
    required this.zone,
    required this.spot,
    required this.weight,
    required this.truckBin,
    required this.loadedDate,
    required this.loadType,
    required this.warehouse,
    required this.loadedBy,
    required this.stagedDate,
    required this.stagedBin,
    required this.quantity,
    required this.legacyItem,
    required this.itemCode,
  });

  factory DockLoadingPalletsModel.fromJson(List<dynamic> json) {
    return DockLoadingPalletsModel(
      soCode: json[1]?.toString() ?? '',
      palletID: json[1]?.toString() ?? '',
      zone: json[0]?.toString() ?? '',
      spot: json[0]?.toString() ?? '',
      weight: json[0]?.toString() ?? '',
      truckBin: json[0]?.toString() ?? '',
      loadedDate: json[0]?.toString() ?? '',
      loadType: json[0]?.toString() ?? '',
      warehouse: json[0]?.toString() ?? '',
      loadedBy: json[0]?.toString() ?? '',
      stagedDate: json[0]?.toString() ?? '',
      stagedBin: json[0]?.toString() ?? '',
      quantity: json[0]?.toString() ?? '',
      legacyItem: json[0]?.toString() ?? '',
      itemCode: json[0]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['soCode'] = soCode;
    data['palletID'] = palletID;
    data['zone'] = zone;
    data['spot'] = spot;
    data['weight'] = weight;
    data['truckBin'] = truckBin;
    data['loadedDate'] = loadedDate;
    data['loadType'] = loadType;
    data['warehouse'] = warehouse;
    data['loadedBy'] = loadedBy;
    data['stagedDate'] = stagedDate;
    data['stagedBin'] = stagedBin;
    data['quantity'] = quantity;
    data['legacyItem'] = legacyItem;
    data['itemCode'] = itemCode;
    return data;
  }
}
