///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ItemTotalModel {
  String warehouse;
  String category;
  String kpQTYTotal;
  String itemCode;
  String legacyItem;
  String pickQty;
  String qtfDIFF;
  String palletCount;
  String palletTotal;
  String nsQTYTotal;


  ItemTotalModel({
    required this.palletCount,
    required this.itemCode,
    required this.legacyItem,
    required this.palletTotal,
    required this.kpQTYTotal,
    required this.pickQty,
    required this.qtfDIFF,
    required this.warehouse,
    required this.category,
    required this.nsQTYTotal,
  });

  factory ItemTotalModel.fromJson(List<dynamic> json) {
    return ItemTotalModel(
      itemCode: json[1]?.toString() ?? '',
      legacyItem: json[14]?.toString() ?? '',
      warehouse: json[8]?.toString() ?? '',
      category: json[3]?.toString() ?? '',
      kpQTYTotal: json[11]?.toString() ?? '',
      pickQty: json[29]?.toString() ?? '',
      qtfDIFF: json[30]?.toString() ?? '',
      palletCount: json[31]?.toString() ?? '',
      palletTotal: json[4]?.toString() ?? '',
      nsQTYTotal: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['palletCount'] = palletCount;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['palletTotal'] = palletTotal;
    data['kpQTYTotal'] = kpQTYTotal;
    data['pickQty'] = pickQty;
    data['qtfDIFF'] = qtfDIFF;
    data['warehouse'] = warehouse;
    data['category'] = category;
    return data;
  }
}
