///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ToQueueModel {
  String to;
  String caseQty;
  String container;
  String ltlPalletQty;
  String tlPalletQty;
  String warehouseFrom;
  String warehouseTo;
  String tranDate;
  String shipDate;
  String pickStarted;
  String pickStartedBy;
  String pCompletedDate;
  String pCompletedBy;
  String pickTime;
  String expectedPickTime;
  String duration;
  String auditStartedBy;
  String auditStartDate;
  String transferMemo;
  String usersAssigned;

  ToQueueModel({
    required this.pickTime,
    required this.caseQty,
    required this.auditStartDate,
    required this.container,
    required this.usersAssigned,
    required this.pCompletedDate,
    required this.transferMemo,
    required this.auditStartedBy,
    required this.warehouseTo,
    required this.pickStartedBy,
    required this.shipDate,
    required this.duration,
    required this.to,
    required this.expectedPickTime,
    required this.pCompletedBy,
    required this.pickStarted,
    required this.tranDate,
    required this.warehouseFrom,
    required this.ltlPalletQty,
    required this.tlPalletQty,
  });

  factory ToQueueModel.fromJson(List<dynamic> json) {
    return ToQueueModel(
      caseQty: json[1]?.toString() ?? '',
      container: json[2]?.toString() ?? '',
      pickTime: json[3]?.toString() ?? '',
      usersAssigned: json[6]?.toString() ?? '',
      pCompletedDate: json[5]?.toString() ?? '',
      transferMemo: json[7]?.toString() ?? '',
      auditStartDate: json[8]?.toString() ?? '',
      auditStartedBy: json[10]?.toString() ?? '',
      warehouseTo: json[10]?.toString() ?? '',
      pickStartedBy: json[10]?.toString() ?? '',
      shipDate: json[10]?.toString() ?? '',
      duration: json[10]?.toString() ?? '',
      to: json[10]?.toString() ?? '',
      pCompletedBy: json[10]?.toString() ?? '',
      expectedPickTime: json[10]?.toString() ?? '',
      pickStarted: json[10]?.toString() ?? '',
      tranDate: json[10]?.toString() ?? '',
      warehouseFrom: json[10]?.toString() ?? '',
      ltlPalletQty: json[10]?.toString() ?? '',
      tlPalletQty: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pickTime'] = pickTime;
    data['caseQty'] = caseQty;
    data['auditStartDate'] = auditStartDate;
    data['container'] = container;
    data['usersAssigned'] = usersAssigned;
    data['pCompletedDate'] = pCompletedDate;
    data['transferMemo'] = transferMemo;
    data['auditStartedBy'] = auditStartedBy;
    data['warehouseTo'] = warehouseTo;
    data['pickStartedBy'] = pickStartedBy;
    data['shipDate'] = shipDate;
    data['duration'] = duration;
    data['to'] = to;
    data['expectedPickTime'] = expectedPickTime;
    data['pCompletedBy'] = pCompletedBy;
    data['pickStarted'] = pickStarted;
    data['tranDate'] = tranDate;
    data['warehouseFrom'] = warehouseFrom;
    data['ltlPalletQty'] = ltlPalletQty;
    data['tlPalletQty'] = tlPalletQty;
    return data;
  }
}
