///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class YardContainersModel {
  String loc;
  String container;
  String duration;
  String memoInYard;
  String receiveStart;
  String firstLabelBy;
  String receiveStartBy;
  String dateInYard;
  String inYardBy;
  String inYardDate;
  String vendor;
  String po;
  String invoiceDate;
  String etaWarehouse;
  String etaPort;
  String inv;

  YardContainersModel({
    required this.vendor,
    required this.etaPort,
    required this.container,
    required this.inYardBy,
    required this.inv,
    required this.etaWarehouse,
    required this.memoInYard,
    required this.dateInYard,
    required this.firstLabelBy,
    required this.invoiceDate,
    required this.loc,
    required this.po,
    required this.inYardDate,
    required this.receiveStartBy,
    required this.receiveStart,
    required this.duration,
  });

  factory YardContainersModel.fromJson(List<dynamic> json) {
    return YardContainersModel(
      container: json[2]?.toString() ?? '',
      vendor: json[3]?.toString() ?? '',
      inYardBy: json[5]?.toString() ?? '',
      inv: json[7]?.toString() ?? '',
      etaPort: json[8]?.toString() ?? '',
      etaWarehouse: json[10]?.toString() ?? '',
      memoInYard: json[10]?.toString() ?? '',
      dateInYard: json[10]?.toString() ?? '',
      firstLabelBy: json[10]?.toString() ?? '',
      invoiceDate: json[10]?.toString() ?? '',
      loc: json[10]?.toString() ?? '',
      inYardDate: json[10]?.toString() ?? '',
      po: json[10]?.toString() ?? '',
      receiveStartBy: json[10]?.toString() ?? '',
      receiveStart: json[10]?.toString() ?? '',
      duration: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['vendor'] = vendor;
    data['etaPort'] = etaPort;
    data['container'] = container;
    data['inYardBy'] = inYardBy;
    data['inv'] = inv;
    data['etaWarehouse'] = etaWarehouse;
    data['memoInYard'] = memoInYard;
    data['dateInYard'] = dateInYard;
    data['firstLabelBy'] = firstLabelBy;
    data['invoiceDate'] = invoiceDate;
    data['loc'] = loc;
    data['po'] = po;
    data['inYardDate'] = inYardDate;
    data['receiveStartBy'] = receiveStartBy;
    data['receiveStart'] = receiveStart;
    data['duration'] = duration;
    return data;
  }
}
