///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ContainerInventoryModel {
  String warehouse;
  String itemCode;
  String container;
  String legacyItem;
  String quantity;
  String totalQty;
  String dateInYard;
  String po;
  String etaWarehouse;
  String etaPort;
  String lfd;

  ContainerInventoryModel({
    required this.itemCode,
    required this.etaPort,
    required this.container,
    required this.lfd,
    required this.etaWarehouse,
    required this.dateInYard,
    required this.warehouse,
    required this.po,
    required this.totalQty,
    required this.quantity,
    required this.legacyItem,
  });

  factory ContainerInventoryModel.fromJson(List<dynamic> json) {
    return ContainerInventoryModel(
      itemCode: json[1]?.toString() ?? '',
      container: json[2]?.toString() ?? '',
      lfd: json[6]?.toString() ?? '',
      etaPort: json[8]?.toString() ?? '',
      etaWarehouse: json[10]?.toString() ?? '',
      dateInYard: json[10]?.toString() ?? '',
      warehouse: json[10]?.toString() ?? '',
      po: json[10]?.toString() ?? '',
      totalQty: json[10]?.toString() ?? '',
      quantity: json[10]?.toString() ?? '',
      legacyItem: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itemCode'] = itemCode;
    data['etaPort'] = etaPort;
    data['container'] = container;
    data['lfd'] = lfd;
    data['etaWarehouse'] = etaWarehouse;
    data['dateInYard'] = dateInYard;
    data['warehouse'] = warehouse;
    data['po'] = po;
    data['totalQty'] = totalQty;
    data['quantity'] = quantity;
    data['legacyItem'] = legacyItem;
    return data;
  }
}
