///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InventoryMovementModel {
  String lpn;
  String bin;
  String quantity;
  String itemCode;
  String legacyItem;
  String addedDate;
  String type;
  String addedBy;
  String boxID;
  String bulkPickItemId;
  String soPackId;
  String so;


  InventoryMovementModel({
    required this.addedBy,
    required this.itemCode,
    required this.legacyItem,
    required this.boxID,
    required this.bulkPickItemId,
    required this.quantity,
    required this.addedDate,
    required this.type,
    required this.lpn,
    required this.bin,
    required this.soPackId,
    required this.so,
  });

  factory InventoryMovementModel.fromJson(List<dynamic> json) {
    return InventoryMovementModel(
      itemCode: json[1]?.toString() ?? '',
      legacyItem: json[14]?.toString() ?? '',
      lpn: json[8]?.toString() ?? '',
      bin: json[3]?.toString() ?? '',
      quantity: json[11]?.toString() ?? '',
      addedDate: json[29]?.toString() ?? '',
      type: json[30]?.toString() ?? '',
      addedBy: json[31]?.toString() ?? '',
      boxID: json[4]?.toString() ?? '',
      bulkPickItemId: json[32]?.toString() ?? '',
      soPackId: json[6]?.toString() ?? '',
      so: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['addedBy'] = addedBy;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['boxID'] = boxID;
    data['bulkPickItemId'] = bulkPickItemId;
    data['quantity'] = quantity;
    data['addedDate'] = addedDate;
    data['type'] = type;
    data['lpn'] = lpn;
    data['bin'] = bin;
    data['so'] = so;
    return data;
  }
}
