///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DoManifestHistoryModel {
  String ref;
  String pickUpDate;
  String pickUpDriver;
  String returnDate;
  String returnDriver;
  String address;
  String route;

  DoManifestHistoryModel({
    required this.ref,
    required this.pickUpDate,
    required this.pickUpDriver,
    required this.returnDate,
    required this.returnDriver,
    required this.address,
    required this.route,
  });

  factory DoManifestHistoryModel.fromJson(List<dynamic> json) {
    return DoManifestHistoryModel(
      ref: json[1]?.toString() ?? '',
      pickUpDate: json[2]?.toString() ?? '',
      pickUpDriver: json[3]?.toString() ?? '',
      returnDate: json[6]?.toString() ?? '',
      returnDriver: json[5]?.toString() ?? '',
      address: json[7]?.toString() ?? '',
      route: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ref'] = ref;
    data['pickUpDate'] = pickUpDate;
    data['pickUpDriver'] = pickUpDriver;
    data['returnDate'] = returnDate;
    data['returnDriver'] = returnDriver;
    data['address'] = address;
    data['route'] = route;
    return data;
  }
}
