///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BinCountAdjustmentExpansionModel {
  String bin;
  String updateDate;
  String updateBy;
  String memo;
  String quantity;
  String reason;
  String createdBy;

  BinCountAdjustmentExpansionModel({
    required this.updateBy,
    required this.updateDate,
    required this.createdBy,
    required this.bin,
    required this.quantity,
    required this.memo,
    required this.reason,
  });

  factory BinCountAdjustmentExpansionModel.fromJson(List<dynamic> json) {
    return BinCountAdjustmentExpansionModel(
      bin: json[28]?.toString() ?? '',
      updateDate: json[28]?.toString() ?? '',
      updateBy: json[14]?.toString() ?? '',
      createdBy: json[8]?.toString() ?? '',
      quantity: json[18]?.toString() ?? '',
      memo: json[18]?.toString() ?? '',
      reason: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['updateBy'] = updateBy;
    data['updateDate'] = updateDate;
    data['createdBy'] = createdBy;
    data['bin'] = bin;
    data['quantity'] = quantity;
    data['memo'] = memo;
    data['reason'] = reason;
    return data;
  }
}
