///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BinCountAdjustmentModel {
  String warehouse;
  String lpn;
  String bin;
  String itemCode;
  String cycleCountId;
  String verify;
  String legacyItem;
  String status;
  String qty;
  String user;

  BinCountAdjustmentModel({
    required this.bin,
    required this.lpn,
    required this.cycleCountId,
    required this.warehouse,
    required this.verify,
    required this.itemCode,
    required this.legacyItem,
    required this.status,
    required this.qty,
    required this.user,
  });

  factory BinCountAdjustmentModel.fromJson(List<dynamic> json) {
    return BinCountAdjustmentModel(
      warehouse: json[28]?.toString() ?? '',
      lpn: json[28]?.toString() ?? '',
      bin: json[14]?.toString() ?? '',
      cycleCountId: json[26]?.toString() ?? '',
      verify: json[18]?.toString() ?? '',
      itemCode: json[18]?.toString() ?? '',
      legacyItem: json[18]?.toString() ?? '',
      status: json[18]?.toString() ?? '',
      qty: json[18]?.toString() ?? '',
      user: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['lpn'] = lpn;
    data['cycleCountId'] = cycleCountId;
    data['warehouse'] = warehouse;
    data['verify'] = verify;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['status'] = status;
    data['qty'] = qty;
    data['user'] = user;
    return data;
  }
}
