///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BPTOSLogModel {
  String bp;
  String soCode;
  String status;
  String po;
  String warehouse;
  String itemCode;
  String legacyItem;
  String ordQty;
  String tosQty;
  String onHandQty;
  String etaWarehouse;
  String bpAddDate;
  String pickQty;
  String salesRep;
  String customerName;

  BPTOSLogModel({
    required this.pickQty,
    required this.itemCode,
    required this.tosQty,
    required this.etaWarehouse,
    required this.bpAddDate,
    required this.onHandQty,
    required this.bp,
    required this.legacyItem,
    required this.soCode,
    required this.ordQty,
    required this.salesRep,
    required this.customerName,
    required this.warehouse,
    required this.po,
    required this.status,
  });

  factory BPTOSLogModel.fromJson(List<dynamic> json) {
    return BPTOSLogModel(
      soCode: json[28]?.toString() ?? '',
      pickQty: json[4]?.toString() ?? '',
      itemCode: json[14]?.toString() ?? '',
      tosQty: json[0]?.toString() ?? '',
      etaWarehouse: json[6]?.toString() ?? '',
      bpAddDate: json[7]?.toString() ?? '',
      onHandQty: json[12]?.toString() ?? '',
      bp: json[26]?.toString() ?? '',
      legacyItem: json[3]?.toString() ?? '',
      ordQty: json[18]?.toString() ?? '',
      salesRep: json[3]?.toString() ?? '',
      customerName: json[18]?.toString() ?? '',
      warehouse: json[18]?.toString() ?? '',
      po: json[18]?.toString() ?? '',
      status: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pickQty'] = pickQty;
    data['itemCode'] = itemCode;
    data['tosQty'] = tosQty;
    data['etaWarehouse'] = etaWarehouse;
    data['bpAddDate'] = bpAddDate;
    data['onHandQty'] = onHandQty;
    data['bp'] = bp;
    data['legacyItem'] = legacyItem;
    data['soCode'] = soCode;
    data['ordQty'] = ordQty;
    data['salesRep'] = salesRep;
    data['customerName'] = customerName;
    data['warehouse'] = warehouse;
    data['po'] = po;
    data['status'] = status;
    return data;
  }
}
