///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NSAdjustmentReviewModel {
  String warehouse;
  String description;
  String itemType;
  String itemCode;
  String amtDiff;
  String createdBy;
  String pickQTY;
  String qtyDiff;
  String qtyDiff2;
  String avgCost;
  String mainMemo;
  String lineMemo;
  String legacyItem;
  String createDate;
  String countQTY;
  String adjustmentID;
  String internalID;
  String kpQTY;
  String nsQTY;

  NSAdjustmentReviewModel({
    required this.itemType,
    required this.description,
    required this.createdBy,
    required this.pickQTY,
    required this.amtDiff,
    required this.qtyDiff,
    required this.qtyDiff2,
    required this.avgCost,
    required this.warehouse,
    required this.mainMemo,
    required this.lineMemo,
    required this.itemCode,
    required this.legacyItem,
    required this.createDate,
    required this.countQTY,
    required this.adjustmentID,
    required this.internalID,
    required this.kpQTY,
    required this.nsQTY,
  });

  factory NSAdjustmentReviewModel.fromJson(List<dynamic> json) {
    return NSAdjustmentReviewModel(
      warehouse: json[28]?.toString() ?? '',
      description: json[28]?.toString() ?? '',
      itemType: json[14]?.toString() ?? '',
      createdBy: json[8]?.toString() ?? '',
      pickQTY: json[26]?.toString() ?? '',
      amtDiff: json[23]?.toString() ?? '',
      qtyDiff: json[3]?.toString() ?? '',
      qtyDiff2: json[3]?.toString() ?? '',
      avgCost: json[3]?.toString() ?? '',
      mainMemo: json[18]?.toString() ?? '',
      lineMemo: json[18]?.toString() ?? '',
      itemCode: json[18]?.toString() ?? '',
      legacyItem: json[18]?.toString() ?? '',
      createDate: json[18]?.toString() ?? '',
      countQTY: json[18]?.toString() ?? '',
      adjustmentID: json[18]?.toString() ?? '',
      internalID: json[18]?.toString() ?? '',
      kpQTY: json[18]?.toString() ?? '',
      nsQTY: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itemType'] = itemType;
    data['description'] = description;
    data['createdBy'] = createdBy;
    data['pickQTY'] = pickQTY;
    data['amtDiff'] = amtDiff;
    data['qtyDiff'] = qtyDiff;
    data['qtyDiff2'] = qtyDiff2;
    data['avgCost'] = avgCost;
    data['warehouse'] = warehouse;
    data['mainMemo'] = mainMemo;
    data['lineMemo'] = lineMemo;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['createDate'] = createDate;
    data['countQTY'] = countQTY;
    data['adjustmentID'] = adjustmentID;
    data['internalID'] = internalID;
    data['nsQTY'] = nsQTY;
    data['kpQTY'] = kpQTY;
    return data;
  }
}
