///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InternalRequestReturnListModel {
  String warehouse;
  String lpn;
  String bpnBin;
  String notes;
  String itemCode;
  String bin;
  String nsDepartment;
  String createdBy;
  String createdDate;
  String nsAdjust;
  String adjustmentDate;
  String adjustmentBy;
  String mainMemo;
  String lineMemo;
  String legacyItem;
  String description;
  String qty;


  InternalRequestReturnListModel({
    required this.bin,
    required this.lpn,
    required this.bpnBin,
    required this.notes,
    required this.createdDate,
    required this.nsDepartment,
    required this.nsAdjust,
    required this.adjustmentDate,
    required this.adjustmentBy,
    required this.warehouse,
    required this.mainMemo,
    required this.lineMemo,
    required this.createdBy,
    required this.itemCode,
    required this.legacyItem,
    required this.description,
    required this.qty,
  });

  factory InternalRequestReturnListModel.fromJson(List<dynamic> json) {
    return InternalRequestReturnListModel(
      warehouse: json[28]?.toString() ?? '',
      lpn: json[28]?.toString() ?? '',
      bin: json[14]?.toString() ?? '',
      bpnBin: json[8]?.toString() ?? '',
      notes: json[8]?.toString() ?? '',
      createdDate: json[26]?.toString() ?? '',
      nsDepartment: json[23]?.toString() ?? '',
      nsAdjust: json[3]?.toString() ?? '',
      adjustmentDate: json[3]?.toString() ?? '',
      adjustmentBy: json[3]?.toString() ?? '',
      mainMemo: json[18]?.toString() ?? '',
      lineMemo: json[18]?.toString() ?? '',
      createdBy: json[18]?.toString() ?? '',
      itemCode: json[18]?.toString() ?? '',
      legacyItem: json[18]?.toString() ?? '',
      description: json[18]?.toString() ?? '',
      qty: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['lpn'] = lpn;
    data['bpnBin'] = bpnBin;
    data['notes'] = notes;
    data['createdDate'] = createdDate;
    data['nsDepartment'] = nsDepartment;
    data['nsAdjust'] = nsAdjust;
    data['adjustmentDate'] = adjustmentDate;
    data['adjustmentBy'] = adjustmentBy;
    data['warehouse'] = warehouse;
    data['mainMemo'] = mainMemo;
    data['lineMemo'] = lineMemo;
    data['createdBy'] = createdBy;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['description'] = description;
    data['qty'] = qty;
    return data;
  }
}
