///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InternalRequestReturnListExpansionModel {
  String lpn;
  String bin;
  String createdBy;
  String createdDate;
  String qty;


  InternalRequestReturnListExpansionModel({
    required this.bin,
    required this.lpn,
    required this.createdBy,
    required this.qty,
    required this.createdDate,
  });

  factory InternalRequestReturnListExpansionModel.fromJson(List<dynamic> json) {
    return InternalRequestReturnListExpansionModel(
      lpn: json[28]?.toString() ?? '',
      bin: json[14]?.toString() ?? '',
      createdDate: json[26]?.toString() ?? '',
      createdBy: json[18]?.toString() ?? '',
      qty: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['lpn'] = lpn;
    data['createdDate'] = createdDate;
    data['createdBy'] = createdBy;
    data['qty'] = qty;
    return data;
  }
}
