///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HistoryPhotoOverrideModel {
  String override;
  String user;
  String date;


  HistoryPhotoOverrideModel({
    required this.date,
    required this.user,
    required this.override,
  });

  factory HistoryPhotoOverrideModel.fromJson(List<dynamic> json) {
    return HistoryPhotoOverrideModel(
      override: json[2]?.toString() ?? '',
      date: json[3]?.toString() ?? '',
      user: json[12]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['user'] = user;
    data['override'] = override;
    return data;
  }
}
