///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HistoryPalletsExpansionModel {
  String itemCode;
  String legacy;
  String description;
  String fulFilledQty;
  String detaPalletIDil;
  String createDate;
  String pickBin;
  String boxID;
  String createdBy;


  HistoryPalletsExpansionModel({
    required this.createDate,
    required this.pickBin,
    required this.createdBy,
    required this.description,
    required this.fulFilledQty,
    required this.detaPalletIDil,
    required this.legacy,
    required this.boxID,
    required this.itemCode,
  });

  factory HistoryPalletsExpansionModel.fromJson(List<dynamic> json) {
    return HistoryPalletsExpansionModel(
      itemCode: json[2]?.toString() ?? '',
      createDate: json[8]?.toString() ?? '',
      pickBin: json[11]?.toString() ?? '',
      description: json[3]?.toString() ?? '',
      fulFilledQty: json[4]?.toString() ?? '',
      detaPalletIDil: json[10]?.toString() ?? '',
      legacy: json[12]?.toString() ?? '',
      boxID: json[6]?.toString() ?? '',
      createdBy: json[7]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createDate'] = createDate;
    data['pickBin'] = pickBin;
    data['createdBy'] = createdBy;
    data['description'] = description;
    data['fulFilledQty'] = fulFilledQty;
    data['detaPalletIDil'] = detaPalletIDil;
    data['legacy'] = legacy;
    data['boxID'] = boxID;
    data['itemCode'] = itemCode;
    return data;
  }
}
