///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HistoryPalletsModel {
  String action;
  String packId;
  String pickBy;
  String pickDate;
  String pickBin;
  String boxCNT;
  String weight;


  HistoryPalletsModel({
    required this.pickDate,
    required this.pickBin,
    required this.weight,
    required this.pickBy,
    required this.packId,
    required this.boxCNT,
    required this.action,
  });

  factory HistoryPalletsModel.fromJson(List<dynamic> json) {
    return HistoryPalletsModel(
      action: json[0]?.toString() ?? '',
      pickDate: json[3]?.toString() ?? '',
      pickBin: json[4]?.toString() ?? '',
      pickBy: json[2]?.toString() ?? '',
      packId: json[1]?.toString() ?? '',
      boxCNT: json[6]?.toString() ?? '',
      weight: json[7]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pickDate'] = pickDate;
    data['pickBin'] = pickBin;
    data['weight'] = weight;
    data['pickBy'] = pickBy;
    data['packId'] = packId;
    data['boxCNT'] = boxCNT;
    data['action'] = action;
    return data;
  }
}
