///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ItemCodeModel {
  String bin;
  String type;
  String license;
  String quantity;
  String holdStatus;

  ItemCodeModel({
    required this.bin,
    required this.type,
    required this.license,
    required this.quantity,
    required this.holdStatus,
  });

  factory ItemCodeModel.fromJson(List<dynamic> json) {
    return ItemCodeModel(
      bin: json[0]?.toString() ?? '',
      type: json[3]?.toString() ?? '',
      license: json[1]?.toString() ?? '',
      quantity: json[2]?.toString() ?? '',
      holdStatus: json[4]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['type'] = type;
    data['license'] = license;
    data['quantity'] = quantity;
    data['holdStatus'] = holdStatus;
    return data;
  }
}
