///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PickingListModel {
  String itemCode;
  String legacyItem;
  String ordQty;
  String boxQty;
  String pcsQty;
  String filledQty;
  String auditQty;
  String nsFilledQty;
  String balance;
  String comp;
  String unitCase;
  String description;
  String whNotes;
  String mark;
  String markUser;
  String location;
  String s;
  String action;

  PickingListModel({
    required this.auditQty,
    required this.nsFilledQty,
    required this.comp,
    required this.itemCode,
    required this.legacyItem,
    required this.unitCase,
    required this.whNotes,
    required this.ordQty,
    required this.boxQty,
    required this.pcsQty,
    required this.filledQty,
    required this.balance,
    required this.mark,
    required this.markUser,
    required this.description,
    required this.s,
    required this.action,
    required this.location,
  });

  factory PickingListModel.fromJson(List<dynamic> json) {
    return PickingListModel(
      auditQty: json[1]?.toString() ?? '',
      nsFilledQty: json[42]?.toString() ?? '',
      comp: json[0]?.toString() ?? '',
      itemCode: json[2]?.toString() ?? '',
      legacyItem: json[22]?.toString() ?? '',
      unitCase: json[29]?.toString() ?? '',
      whNotes: json[0]?.toString() ?? '',
      ordQty: json[37]?.toString() ?? '',
      boxQty: json[10]?.toString() ?? '',
      pcsQty: json[11]?.toString() ?? '',
      filledQty: json[11]?.toString() ?? '',
      balance: json[4]?.toString() ?? '',
      mark: '00:00',
      markUser: json[23]?.toString() ?? '',
      description: json[7]?.toString() ?? '',
      s: json[28]?.toString() ?? '',
      action: json[28]?.toString() ?? '',
      location: json[33]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['auditQty'] = auditQty;
    data['nsFilledQty'] = nsFilledQty;
    data['comp'] = comp;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['unitCase'] = unitCase;
    data['whNotes'] = whNotes;
    data['ordQty'] = ordQty;
    data['boxQty'] = boxQty;
    data['pcsQty'] = pcsQty;
    data['filledQty'] = filledQty;
    data['balance'] = balance;
    data['mark'] = mark;
    data['markUser'] = markUser;
    data['description'] = description;
    data['s'] = s;
    data['action'] = action;
    data['location'] = location;
    return data;
  }
}
