///
/// Code generated by jsonwarehouseDartModel https://ashamp.github.io/jsonwarehouseDartModel/
///
class ManifestHistoryV2Model {
  String priority;
  String warehouse;
  String route;
  String truck;
  String truckType;
  String trailer;
  String driver;
  String totalRouteTimer;
  String loader;
  String departureSchedule;
  String stops;
  String pallets;
  String weight;

  ManifestHistoryV2Model({
    required this.stops,
    required this.pallets,
    required this.warehouse,
    required this.weight,
    required this.departureSchedule,
    required this.loader,
    required this.driver,
    required this.priority,
    required this.trailer,
    required this.route,
    required this.truckType,
    required this.totalRouteTimer,
    required this.truck,
  });

  factory ManifestHistoryV2Model.fromJson(List<dynamic> json) {
    return ManifestHistoryV2Model(
      stops: json[1]?.toString() ?? '',
      pallets: json[2]?.toString() ?? '',
      warehouse: json[10]?.toString() ?? '',
      weight: json[10]?.toString() ?? '',
      departureSchedule: json[10]?.toString() ?? '',
      loader: json[10]?.toString() ?? '',
      totalRouteTimer: json[8]?.toString() ?? '',
      driver: json[10]?.toString() ?? '',
      priority: json[10]?.toString() ?? '',
      trailer: json[10]?.toString() ?? '',
      route: json[10]?.toString() ?? '',
      truckType: json[10]?.toString() ?? '',
      truck: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> warehouseJson() {
    final data = <String, dynamic>{};
    data['stops'] = stops;
    data['pallets'] = pallets;
    data['warehouse'] = warehouse;
    data['weight'] = weight;
    data['departureSchedule'] = departureSchedule;
    data['loader'] = loader;
    data['truck'] = truck;
    data['driver'] = driver;
    data['priority'] = priority;
    data['trailer'] = trailer;
    data['route'] = route;
    data['totalRouteTimer'] = totalRouteTimer;
    data['truckType'] = truckType;
    return data;
  }
}
