///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NonShippedModel {
  String wh;
  String order;
  String type;
  String customer;
  String toWH;

  NonShippedModel({
    required this.wh,
    required this.order,
    required this.type,
    required this.customer,
    required this.toWH,
  });

  factory NonShippedModel.fromJson(List<dynamic> json) {
    return NonShippedModel(
      wh: json[1]?.toString() ?? '',
      order: json[3]?.toString() ?? '',
      type: json[0]?.toString() ?? '',
      customer: json[2]?.toString() ?? '',
      toWH: json[4]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['wh'] = wh;
    data['order'] = order;
    data['type'] = type;
    data['customer'] = customer;
    data['toWH'] = toWH;
    return data;
  }
}
