///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FulfillmentAdjustmentRequestModel {
  String warehouse;
  String diff;
  String onHand;
  String itemCode;
  String action;
  String createdBy;
  String amount;
  String nsAdjust;
  String adjustmentDate;
  String adjustmentBy;
  String mainMemo;
  String lineMemo;
  String legacyItem;
  String createDate;
  String averageCost;
  String so;
  String quantity;
  String originalDiff;

  FulfillmentAdjustmentRequestModel({
    required this.onHand,
    required this.diff,
    required this.createdBy,
    required this.amount,
    required this.action,
    required this.nsAdjust,
    required this.adjustmentDate,
    required this.adjustmentBy,
    required this.warehouse,
    required this.mainMemo,
    required this.lineMemo,
    required this.itemCode,
    required this.legacyItem,
    required this.createDate,
    required this.averageCost,
    required this.so,
    required this.quantity,
    required this.originalDiff,
  });

  factory FulfillmentAdjustmentRequestModel.fromJson(List<dynamic> json) {
    return FulfillmentAdjustmentRequestModel(
      warehouse: json[28]?.toString() ?? '',
      diff: json[28]?.toString() ?? '',
      onHand: json[14]?.toString() ?? '',
      createdBy: json[8]?.toString() ?? '',
      amount: json[26]?.toString() ?? '',
      action: json[23]?.toString() ?? '',
      nsAdjust: json[3]?.toString() ?? '',
      adjustmentDate: json[3]?.toString() ?? '',
      adjustmentBy: json[3]?.toString() ?? '',
      mainMemo: json[18]?.toString() ?? '',
      lineMemo: json[18]?.toString() ?? '',
      itemCode: json[18]?.toString() ?? '',
      legacyItem: json[18]?.toString() ?? '',
      createDate: json[18]?.toString() ?? '',
      averageCost: json[18]?.toString() ?? '',
      so: json[18]?.toString() ?? '',
      quantity: json[18]?.toString() ?? '',
      originalDiff: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['onHand'] = onHand;
    data['diff'] = diff;
    data['createdBy'] = createdBy;
    data['amount'] = amount;
    data['action'] = action;
    data['nsAdjust'] = nsAdjust;
    data['adjustmentDate'] = adjustmentDate;
    data['adjustmentBy'] = adjustmentBy;
    data['warehouse'] = warehouse;
    data['mainMemo'] = mainMemo;
    data['lineMemo'] = lineMemo;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['createDate'] = createDate;
    data['averageCost'] = averageCost;
    data['so'] = so;
    data['quantity'] = quantity;
    data['originalDiff'] = originalDiff;
    return data;
  }
}
