///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InterDeptItemTransferModel {
  String requestID;
  String kpQty;
  String fromDept;
  String itemCode;
  String legacyItem;
  String po;
  String quantity;
  String container;
  String origin;
  String binUpdatedBy;
  String toDept;
  String qty;
  String createdBy;
  String warehouse;
  String lot;
  String binUpdateDate;
  String createDate;
  String sqFT;
  String cube;


  InterDeptItemTransferModel({
    required this.container,
    required this.itemCode,
    required this.legacyItem,
    required this.origin,
    required this.binUpdatedBy,
    required this.fromDept,
    required this.po,
    required this.quantity,
    required this.requestID,
    required this.kpQty,
    required this.toDept,
    required this.qty,
    required this.createdBy,
    required this.warehouse,
    required this.lot,
    required this.binUpdateDate,
    required this.createDate,
    required this.sqFT,
    required this.cube,
  });

  factory InterDeptItemTransferModel.fromJson(List<dynamic> json) {
    return InterDeptItemTransferModel(
      itemCode: json[1]?.toString() ?? '',
      legacyItem: json[14]?.toString() ?? '',
      requestID: json[8]?.toString() ?? '',
      kpQty: json[3]?.toString() ?? '',
      fromDept: json[11]?.toString() ?? '',
      po: json[29]?.toString() ?? '',
      quantity: json[30]?.toString() ?? '',
      container: json[31]?.toString() ?? '',
      origin: json[4]?.toString() ?? '',
      binUpdatedBy: json[32]?.toString() ?? '',
      toDept: json[6]?.toString() ?? '',
      qty: json[6]?.toString() ?? '',
      createdBy: json[6]?.toString() ?? '',
      warehouse: json[6]?.toString() ?? '',
      lot: json[6]?.toString() ?? '',
      binUpdateDate: json[6]?.toString() ?? '',
      createDate: json[6]?.toString() ?? '',
      sqFT: json[6]?.toString() ?? '',
      cube: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['container'] = container;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['origin'] = origin;
    data['binUpdatedBy'] = binUpdatedBy;
    data['fromDept'] = fromDept;
    data['po'] = po;
    data['quantity'] = quantity;
    data['requestID'] = requestID;
    data['kpQty'] = kpQty;
    data['qty'] = qty;
    data['createdBy'] = createdBy;
    data['warehouse'] = warehouse;
    data['lot'] = lot;
    data['binUpdateDate'] = binUpdateDate;
    data['createDate'] = createDate;
    data['sqFT'] = sqFT;
    data['cube'] = cube;
    return data;
  }
}
