///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ToContainersExpansionModel {
  String itemName;
  String legacyItem;
  String amount;
  String quantity;
  String qtyFulfilled;
  String qtyReceived;
  String rate;

  ToContainersExpansionModel({
    required this.qtyFulfilled,
    required this.legacyItem,
    required this.amount,
    required this.rate,
    required this.qtyReceived,
    required this.itemName,
    required this.quantity,
  });

  factory ToContainersExpansionModel.fromJson(List<dynamic> json) {
    return ToContainersExpansionModel(
      legacyItem: json[1]?.toString() ?? '',
      qtyFulfilled: json[3]?.toString() ?? '',
      amount: json[6]?.toString() ?? '',
      rate: json[10]?.toString() ?? '',
      qtyReceived: json[10]?.toString() ?? '',
      itemName: json[10]?.toString() ?? '',
      quantity: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['qtyFulfilled'] = qtyFulfilled;
    data['legacyItem'] = legacyItem;
    data['amount'] = amount;
    data['rate'] = rate;
    data['qtyReceived'] = qtyReceived;
    data['itemName'] = itemName;
    data['quantity'] = quantity;
    return data;
  }
}
