///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ToContainersModel {
  String to;
  String container;
  String status;
  String memo;
  String fromWH;
  String toWH;
  String memoInYard;
  String dateInYard;
  String etaWarehouse;
  String inYardBy;

  ToContainersModel({
    required this.container,
    required this.toWH,
    required this.inYardBy,
    required this.dateInYard,
    required this.to,
    required this.etaWarehouse,
    required this.memoInYard,
    required this.fromWH,
    required this.status,
    required this.memo,
  });

  factory ToContainersModel.fromJson(List<dynamic> json) {
    return ToContainersModel(
      container: json[2]?.toString() ?? '',
      toWH: json[10]?.toString() ?? '',
      inYardBy: json[10]?.toString() ?? '',
      dateInYard: json[10]?.toString() ?? '',
      to: json[10]?.toString() ?? '',
      etaWarehouse: json[10]?.toString() ?? '',
      memoInYard: json[10]?.toString() ?? '',
      fromWH: json[10]?.toString() ?? '',
      status: json[10]?.toString() ?? '',
      memo: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['container'] = container;
    data['toWH'] = toWH;
    data['inYardBy'] = inYardBy;
    data['dateInYard'] = dateInYard;
    data['to'] = to;
    data['etaWarehouse'] = etaWarehouse;
    data['memoInYard'] = memoInYard;
    data['fromWH'] = fromWH;
    data['status'] = status;
    data['memo'] = memo;
    return data;
  }
}
