///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AuditQueueModel {
  String wh;
  String priority;
  String so;
  String orderStatus;
  String shipDate;
  String customerName;
  String shipVia;
  String auditAssignedTo;
  String pickStarted;
  String pickStartedBy;
  String pCompletedBy;
  String pCompletedDate;
  String duration;
  String auditStartedBy;
  String auditors;
  String auditStartDate;
  String fulFillmentBy;
  String fulFillmentDate; 
  String auditEndBy;
  String auditEndDate;

  AuditQueueModel({
    required this.wh,
    required this.priority,
    required this.so,
    required this.orderStatus,
    required this.shipDate,
    required this.customerName,
    required this.shipVia,
    required this.auditAssignedTo,
    required this.pickStarted,
    required this.pickStartedBy,
    required this.pCompletedBy,
    required this.pCompletedDate,
    required this.duration,
    required this.auditStartedBy,
    required this.auditors,
    required this.auditStartDate,
    required this.fulFillmentBy,
    required this.fulFillmentDate,
    required this.auditEndBy,
    required this.auditEndDate,
  });

  factory AuditQueueModel.fromJson(List<dynamic> json) {
    return AuditQueueModel(
      wh: json[2]?.toString() ?? '',
      priority: json[3]?.toString() ?? '',
      so: json[1]?.toString() ?? '',
      orderStatus: json[4]?.toString() ?? '',
      shipDate: json[5]?.toString() ?? '',
      customerName: json[6]?.toString() ?? '',
      shipVia: json[7]?.toString() ?? '',
      auditAssignedTo: json[14]?.toString() ?? '',
      pickStarted: json[9]?.toString() ?? '',
      pickStartedBy: json[10]?.toString() ?? '',
      pCompletedBy: json[12]?.toString() ?? '',
      pCompletedDate: json[11]?.toString() ?? '',
      duration: json[13]?.toString() ?? '',
      auditStartedBy: json[14]?.toString() ?? '',
      auditors: json[26]?.toString() ?? '',
      auditStartDate: json[15]?.toString() ?? '',
      fulFillmentBy: json[20]?.toString() ?? '',
      fulFillmentDate: json[21]?.toString() ?? '',
      auditEndBy: json[22]?.toString() ?? '',
      auditEndDate: json[13]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['wh'] = wh;
    data['priority'] = priority;
    data['so'] = so;
    data['orderStatus'] = orderStatus;
    data['shipDate'] = shipDate;
    data['customerName'] = customerName;
    data['shipVia'] = shipVia;
    data['auditAssignedTo'] = auditAssignedTo;
    data['pickStarted'] = pickStarted;
    data['pickStartedBy'] = pickStartedBy;
    data['pCompletedBy'] = pCompletedBy;
    data['pCompletedDate'] = pCompletedDate;
    data['duration'] = duration;
    data['auditStartedBy'] = auditStartedBy;
    data['auditors'] = auditors;
    data['auditStartDate'] = auditStartDate;
    data['fulFillmentBy'] = fulFillmentBy;
    data['fulFillmentDate'] = fulFillmentDate;
    data['auditEndBy'] = auditEndBy;
    data['auditEndDate'] = auditEndDate;
    return data;
  }
}
