///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SPBPHistoryModel {
  String detail;
  String action;
  String priority;
  String bulkId;
  String loc;
  String so;
  String itemCount;
  String soFF;
  String addedDate;
  String pickStarted;
  String pickStartedBy;
  String pCompletedDate;
  String pCompletedBy;
  String duration;
  String addedBy;
  String pickerAssignedTo;
  String assignCarrier;
  String bpStatus;

  SPBPHistoryModel({
    required this.addedBy,
    required this.so,
    required this.addedDate,
    required this.pickStartedBy,
    required this.pCompletedDate,
    required this.pCompletedBy,
    required this.duration,
    required this.pickStarted,
    required this.detail,
    required this.itemCount,
    required this.action,
    required this.soFF,
    required this.pickerAssignedTo,
    required this.assignCarrier,
    required this.bpStatus,
    required this.loc,
    required this.bulkId,
    required this.priority,
  });

  factory SPBPHistoryModel.fromJson(List<dynamic> json) {
    return SPBPHistoryModel(
      action: json[28]?.toString() ?? '',
      addedBy: json[4]?.toString() ?? '',
      so: json[14]?.toString() ?? '',
      addedDate: json[0]?.toString() ?? '',
      pickStartedBy: json[15]?.toString() ?? '',
      pCompletedDate: json[6]?.toString() ?? '',
      pCompletedBy: json[7]?.toString() ?? '',
      duration: json[8]?.toString() ?? '',
      pickStarted: json[12]?.toString() ?? '',
      detail: json[26]?.toString() ?? '',
      itemCount: json[3]?.toString() ?? '',
      soFF: json[18]?.toString() ?? '',
      pickerAssignedTo: json[23]?.toString() ?? '',
      assignCarrier: json[3]?.toString() ?? '',
      bpStatus: json[18]?.toString() ?? '',
      loc: json[18]?.toString() ?? '',
      bulkId: json[18]?.toString() ?? '',
      priority: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['addedBy'] = addedBy;
    data['so'] = so;
    data['addedDate'] = addedDate;
    data['pickStartedBy'] = pickStartedBy;
    data['pCompletedDate'] = pCompletedDate;
    data['pCompletedBy'] = pCompletedBy;
    data['duration'] = duration;
    data['pickStarted'] = pickStarted;
    data['detail'] = detail;
    data['itemCount'] = itemCount;
    data['action'] = action;
    data['soFF'] = soFF;
    data['pickerAssignedTo'] = pickerAssignedTo;
    data['assignCarrier'] = assignCarrier;
    data['bpStatus'] = bpStatus;
    data['loc'] = loc;
    data['bulkId'] = bulkId;
    data['priority'] = priority;
    return data;
  }
}
