///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SPBPHistoryExpansionModel {
  String so;
  String shipDate;
  String shipVia;
  String loc;
  String customerName;
  String status;
  String shipState;
  String pCompletedDate;
  String salesRep;
  String shipTo;

  SPBPHistoryExpansionModel({
    required this.salesRep,
    required this.so,
    required this.pCompletedDate,
    required this.customerName,
    required this.status,
    required this.shipState,
    required this.shipTo,
    required this.loc,
    required this.shipVia,
    required this.shipDate,
  });

  factory SPBPHistoryExpansionModel.fromJson(List<dynamic> json) {
    return SPBPHistoryExpansionModel(
      salesRep: json[4]?.toString() ?? '',
      so: json[14]?.toString() ?? '',
      pCompletedDate: json[6]?.toString() ?? '',
      customerName: json[26]?.toString() ?? '',
      status: json[3]?.toString() ?? '',
      shipState: json[18]?.toString() ?? '',
      shipTo: json[18]?.toString() ?? '',
      loc: json[18]?.toString() ?? '',
      shipVia: json[18]?.toString() ?? '',
      shipDate: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['salesRep'] = salesRep;
    data['so'] = so;
    data['pCompletedDate'] = pCompletedDate;
    data['customerName'] = customerName;
    data['status'] = status;
    data['shipState'] = shipState;
    data['shipTo'] = shipTo;
    data['loc'] = loc;
    data['shipVia'] = shipVia;
    data['shipDate'] = shipDate;
    return data;
  }
}
