///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PalletIdMovementModel {
  String soCode;
  String legacyItem;
  String palletID;
  String stagedBin;
  String itemCode;
  String quantity;
  String createdBy;
  String createDate;
  String lastMovedBy;
  String lastMovedDate;


  PalletIdMovementModel({
    required this.palletID,
    required this.itemCode,
    required this.stagedBin,
    required this.legacyItem,
    required this.soCode,
    required this.quantity,
    required this.createdBy,
    required this.createDate,
    required this.lastMovedBy,
    required this.lastMovedDate,
  });

  factory PalletIdMovementModel.fromJson(List<dynamic> json) {
    return PalletIdMovementModel(
      palletID: json[1]?.toString() ?? '',
      itemCode: json[3]?.toString() ?? '',
      stagedBin: json[2]?.toString() ?? '',
      legacyItem: json[4]?.toString() ?? '',
      soCode: json[0]?.toString() ?? '',
      quantity: json[5]?.toString() ?? '',
      createdBy: json[6]?.toString() ?? '',
      createDate: json[7]?.toString() ?? '',
      lastMovedBy: json[8]?.toString() ?? '',
      lastMovedDate: json[9]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['palletID'] = palletID;
    data['itemCode'] = itemCode;
    data['stagedBin'] = stagedBin;
    data['legacyItem'] = legacyItem;
    data['soCode'] = soCode;
    data['quantity'] = quantity;
    data['createdBy'] = createdBy;
    data['createDate'] = createDate;
    data['lastMovedBy'] = lastMovedBy;
    data['lastMovedDate'] = lastMovedDate;
    return data;
  }
}
