///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BinCountHistoryModel {
  String id;
  String bin;
  String hi;
  String itemCode;
  String legacyItem;
  String ti;
  String loose;
  String bagCase;
  String source;
  String reason;
  String addedBy;
  String addedDate;
  String license;
  String single;
  String quantity;


  BinCountHistoryModel({
    required this.single,
    required this.itemCode,
    required this.legacyItem,
    required this.bagCase,
    required this.reason,
    required this.addedBy,
    required this.addedDate,
    required this.license,
    required this.source,
    required this.hi,
    required this.bin,
    required this.ti,
    required this.id,
    required this.loose,
    required this.quantity,
  });

  factory BinCountHistoryModel.fromJson(List<dynamic> json) {
    return BinCountHistoryModel(
      id: json[28]?.toString() ?? '',
      single: json[4]?.toString() ?? '',
      itemCode: json[2]?.toString() ?? '',
      legacyItem: json[14]?.toString() ?? '',
      bagCase: json[0]?.toString() ?? '',
      reason: json[15]?.toString() ?? '',
      addedBy: json[6]?.toString() ?? '',
      addedDate: json[7]?.toString() ?? '',
      license: json[8]?.toString() ?? '',
      source: json[12]?.toString() ?? '',
      hi: json[26]?.toString() ?? '',
      bin: json[23]?.toString() ?? '',
      ti: json[3]?.toString() ?? '',
      loose: json[18]?.toString() ?? '',
      quantity: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['single'] = single;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['bagCase'] = bagCase;
    data['reason'] = reason;
    data['addedBy'] = addedBy;
    data['addedDate'] = addedDate;
    data['license'] = license;
    data['source'] = source;
    data['hi'] = hi;
    data['bin'] = bin;
    data['ti'] = ti;
    data['id'] = id;
    data['loose'] = loose;
    data['quantity'] = quantity;
    return data;
  }
}
