///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RackQueueExpansionModel {
  String warehouse;
  String lpn;
  String palletMovementDate;
  String itemCode;
  String fromBin;
  String toBin;
  String qty;
  String legacy;
  String quantity;

  RackQueueExpansionModel({
    required this.palletMovementDate,
    required this.lpn,
    required this.toBin,
    required this.fromBin,
    required this.qty,
    required this.warehouse,
    required this.itemCode,
    required this.legacy,
    required this.quantity,
  });

  factory RackQueueExpansionModel.fromJson(List<dynamic> json) {
    return RackQueueExpansionModel(
      warehouse: json[28]?.toString() ?? '',
      lpn: json[28]?.toString() ?? '',
      palletMovementDate: json[14]?.toString() ?? '',
      toBin: json[8]?.toString() ?? '',
      fromBin: json[23]?.toString() ?? '',
      qty: json[3]?.toString() ?? '',
      itemCode: json[18]?.toString() ?? '',
      legacy: json[18]?.toString() ?? '',
      quantity: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lpn'] = lpn;
    data['toBin'] = toBin;
    data['palletMovementDate'] = palletMovementDate;
    data['fromBin'] = fromBin;
    data['qty'] = qty;
    data['warehouse'] = warehouse;
    data['itemCode'] = itemCode;
    data['legacy'] = legacy;
    data['quantity'] = quantity;
    return data;
  }
}
