///
/// Code generated by jsonwarehouseDartModel https://ashamp.github.io/jsonwarehouseDartModel/
///
class DriverRoutesModel {
  String action;
  String priority;
  String warehouse;
  String stopDuration;
  String palletJack;
  String so;
  String orderType;
  String departureSchedule;
  String stop;
  String truck;
  String palletExchange;
  String route;
  String truckType;
  String status;
  String driver;
  String totalRouteTimer;
  String startTimeStamp;
  String stopTimeStamp;
  String driveDuration;
  String pod;
  String shipDate;
  String address;
  String pickedBy;
  String checkedBy;
  String companyBusinessName;
  String contactPerson;
  String phone;
  String zone;
  String trailer;
  String loadingDock;
  String liftGate;
  String limitedAccess;
  String eMail;
  String terms;
  String mileage;
  String boxCount;
  String trailerAccess;
  String hours;
  String appt;
  String palletCount;
  String totalWeight;
  String customer;
  String category;

  DriverRoutesModel({
    required this.action,
    required this.priority,
    required this.startTimeStamp,
    required this.stopDuration,
    required this.shipDate,
    required this.palletJack,
    required this.pickedBy,
    required this.driver,
    required this.address,
    required this.pod,
    required this.truck,
    required this.status,
    required this.route,
    required this.driveDuration,
    required this.warehouse,
    required this.stopTimeStamp,
    required this.totalRouteTimer,
    required this.truckType,
    required this.boxCount,
    required this.stop,
    required this.so,
    required this.orderType,
    required this.loadingDock,
    required this.palletExchange,
    required this.mileage,
    required this.companyBusinessName,
    required this.trailer,
    required this.phone,
    required this.terms,
    required this.eMail,
    required this.liftGate,
    required this.zone,
    required this.contactPerson,
    required this.checkedBy,
    required this.trailerAccess,
    required this.limitedAccess,
    required this.departureSchedule,
    required this.hours,
    required this.appt,
    required this.palletCount,
    required this.totalWeight,
    required this.customer,
    required this.category,
  });

  factory DriverRoutesModel.fromJson(List<dynamic> json) {
    return DriverRoutesModel(
      action: json[1]?.toString() ?? '',
      priority: json[1]?.toString() ?? '',
      stopDuration: json[1]?.toString() ?? '',
      palletJack: json[2]?.toString() ?? '',
      startTimeStamp: json[3]?.toString() ?? '',
      pickedBy: json[6]?.toString() ?? '',
      driver: json[5]?.toString() ?? '',
      address: json[7]?.toString() ?? '',
      shipDate: json[8]?.toString() ?? '',
      pod: json[10]?.toString() ?? '',
      truck: json[10]?.toString() ?? '',
      status: json[10]?.toString() ?? '',
      route: json[10]?.toString() ?? '',
      driveDuration: json[10]?.toString() ?? '',
      warehouse: json[10]?.toString() ?? '',
      totalRouteTimer: json[10]?.toString() ?? '',
      stopTimeStamp: json[10]?.toString() ?? '',
      truckType: json[10]?.toString() ?? '',
      boxCount: json[10]?.toString() ?? '',
      stop: json[10]?.toString() ?? '',
      so: json[10]?.toString() ?? '',
      orderType: json[10]?.toString() ?? '',
      palletExchange: json[7]?.toString() ?? '',
      mileage: json[10]?.toString() ?? '',
      companyBusinessName: json[10]?.toString() ?? '',
      trailer: json[10]?.toString() ?? '',
      phone: json[10]?.toString() ?? '',
      terms: json[10]?.toString() ?? '',
      trailerAccess: json[10]?.toString() ?? '',
      liftGate: json[10]?.toString() ?? '',
      eMail: json[10]?.toString() ?? '',
      zone: json[10]?.toString() ?? '',
      contactPerson: json[10]?.toString() ?? '',
      checkedBy: json[10]?.toString() ?? '',
      loadingDock: json[10]?.toString() ?? '',
      limitedAccess: json[10]?.toString() ?? '',
      departureSchedule: json[10]?.toString() ?? '',
      hours: json[10]?.toString() ?? '',
      appt: json[10]?.toString() ?? '',
      palletCount: json[10]?.toString() ?? '',
      totalWeight: json[10]?.toString() ?? '',
      customer: json[10]?.toString() ?? '',
      category: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['priority'] = priority;
    data['startTimeStamp'] = startTimeStamp;
    data['stopDuration'] = stopDuration;
    data['shipDate'] = shipDate;
    data['palletJack'] = palletJack;
    data['pickedBy'] = pickedBy;
    data['driver'] = driver;
    data['address'] = address;
    data['pod'] = pod;
    data['truck'] = truck;
    data['status'] = status;
    data['route'] = route;
    data['driveDuration'] = driveDuration;
    data['warehouse'] = warehouse;
    data['stopTimeStamp'] = stopTimeStamp;
    data['totalRouteTimer'] = totalRouteTimer;
    data['truckType'] = truckType;
    data['boxCount'] = boxCount;
    data['stop'] = stop;
    data['so'] = so;
    data['orderType'] = orderType;
    data['loadingDock'] = loadingDock;
    data['palletExchange'] = palletExchange;
    data['mileage'] = mileage;
    data['companyBusinessName'] = companyBusinessName;
    data['trailer'] = trailer;
    data['phone'] = phone;
    data['terms'] = terms;
    data['eMail'] = eMail;
    data['liftGate'] = liftGate;
    data['zone'] = zone;
    data['contactPerson'] = contactPerson;
    data['checkedBy'] = checkedBy;
    data['trailerAccess'] = trailerAccess;
    data['limitedAccess'] = limitedAccess;
    data['departureSchedule'] = departureSchedule;
    data['hours'] = hours;
    data['appt'] = appt;
    data['palletCount'] = palletCount;
    data['totalWeight'] = totalWeight;
    data['customer'] = customer;
    data['category'] = category;
    return data;
  }
}
