///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FreightViewHistoryModel {
  String warehouse;
  String cancelDate;
  String so;
  String type;
  String carrier;
  String shipDate;
  String cost;
  String markUpCost;
  String markUp;
  String lumperFee;
  String roundUp;
  String nsShippingCost;
  String costDifference;
  String palletCount;
  String totalWeight;
  String createDate;
  String createBy;
  String cancelBy;
  String fvSyncStatus;
  String fvSyncError;
  String multipleSO;

  FreightViewHistoryModel({
    required this.totalWeight,
    required this.cancelDate,
    required this.palletCount,
    required this.type,
    required this.fvSyncError,
    required this.nsShippingCost,
    required this.fvSyncStatus,
    required this.cancelBy,
    required this.markUpCost,
    required this.roundUp,
    required this.shipDate,
    required this.createBy,
    required this.warehouse,
    required this.createDate,
    required this.costDifference,
    required this.lumperFee,
    required this.markUp,
    required this.cost,
    required this.so,
    required this.carrier,
    required this.multipleSO,
  });

  factory FreightViewHistoryModel.fromJson(List<dynamic> json) {
    return FreightViewHistoryModel(
      cancelDate: json[1]?.toString() ?? '',
      type: json[2]?.toString() ?? '',
      totalWeight: json[3]?.toString() ?? '',
      fvSyncError: json[6]?.toString() ?? '',
      nsShippingCost: json[5]?.toString() ?? '',
      fvSyncStatus: json[7]?.toString() ?? '',
      palletCount: json[8]?.toString() ?? '',
      cancelBy: json[10]?.toString() ?? '',
      markUpCost: json[10]?.toString() ?? '',
      roundUp: json[10]?.toString() ?? '',
      shipDate: json[10]?.toString() ?? '',
      createBy: json[10]?.toString() ?? '',
      warehouse: json[10]?.toString() ?? '',
      costDifference: json[10]?.toString() ?? '',
      createDate: json[10]?.toString() ?? '',
      lumperFee: json[10]?.toString() ?? '',
      markUp: json[10]?.toString() ?? '',
      cost: json[10]?.toString() ?? '',
      so: json[10]?.toString() ?? '',
      carrier: json[10]?.toString() ?? '',
      multipleSO: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['totalWeight'] = totalWeight;
    data['cancelDate'] = cancelDate;
    data['palletCount'] = palletCount;
    data['type'] = type;
    data['fvSyncError'] = fvSyncError;
    data['nsShippingCost'] = nsShippingCost;
    data['fvSyncStatus'] = fvSyncStatus;
    data['cancelBy'] = cancelBy;
    data['markUpCost'] = markUpCost;
    data['roundUp'] = roundUp;
    data['shipDate'] = shipDate;
    data['createBy'] = createBy;
    data['warehouse'] = warehouse;
    data['createDate'] = createDate;
    data['costDifference'] = costDifference;
    data['lumperFee'] = lumperFee;
    data['markUp'] = markUp;
    data['cost'] = cost;
    data['so'] = so;
    data['carrier'] = carrier;
    data['multipleSO'] = multipleSO;
    return data;
  }
}
