///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SPBulkPickDataTableModel {
  String description;
  String itemIntId;
  String pickBin;
  String scanId;
  String bulkPickWareHouse;
  String itemCode;
  String legacyItem;
  String ordQty;
  String pickQty;

  SPBulkPickDataTableModel({
    required this.pickQty,
    required this.itemCode,
    required this.description,
    required this.legacyItem,
    required this.itemIntId,
    required this.ordQty,
    required this.bulkPickWareHouse,
    required this.scanId,
    required this.pickBin,
  });

  factory SPBulkPickDataTableModel.fromJson(List<dynamic> json) {
    return SPBulkPickDataTableModel(
      itemIntId: json[28]?.toString() ?? '',
      pickQty: json[4]?.toString() ?? '',
      itemCode: json[14]?.toString() ?? '',
      description: json[26]?.toString() ?? '',
      legacyItem: json[3]?.toString() ?? '',
      ordQty: json[18]?.toString() ?? '',
      bulkPickWareHouse: json[18]?.toString() ?? '',
      scanId: json[18]?.toString() ?? '',
      pickBin: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pickQty'] = pickQty;
    data['itemCode'] = itemCode;
    data['description'] = description;
    data['legacyItem'] = legacyItem;
    data['itemIntId'] = itemIntId;
    data['ordQty'] = ordQty;
    data['bulkPickWareHouse'] = bulkPickWareHouse;
    data['scanId'] = scanId;
    data['pickBin'] = pickBin;
    return data;
  }
}
