///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PartialPalletListModel {
  String warehouse;
  String lpn;
  String bin;
  String itemCode;
  String legacyItem;
  String currentQty;
  String receivedQty;
  String ti;
  String hi;
  String palletCount;


  PartialPalletListModel({
    required this.bin,
    required this.lpn,
    required this.currentQty,
    required this.receivedQty,
    required this.itemCode,
    required this.ti,
    required this.warehouse,
    required this.hi,
    required this.legacyItem,
    required this.palletCount,
  });

  factory PartialPalletListModel.fromJson(List<dynamic> json) {
    return PartialPalletListModel(
      warehouse: json[28]?.toString() ?? '',
      bin: json[14]?.toString() ?? '',
      lpn: json[8]?.toString() ?? '',
      currentQty: json[26]?.toString() ?? '',
      receivedQty: json[26]?.toString() ?? '',
      itemCode: json[23]?.toString() ?? '',
      ti: json[3]?.toString() ?? '',
      hi: json[18]?.toString() ?? '',
      legacyItem: json[18]?.toString() ?? '',
      palletCount: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['lpn'] = lpn;
    data['currentQty'] = currentQty;
    data['receivedQty'] = receivedQty;
    data['itemCode'] = itemCode;
    data['ti'] = ti;
    data['warehouse'] = warehouse;
    data['hi'] = hi;
    data['legacyItem'] = legacyItem;
    data['palletCount'] = palletCount;
    return data;
  }
}
