///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ManageRoleModel {
  String roleGroupName;
  String roles;
  String roleId;

  ManageRoleModel({
    required this.roleId,
    required this.roles,
    required this.roleGroupName,
  });

  factory ManageRoleModel.fromJson(Map<String, dynamic> json) {
    return ManageRoleModel(
      roleGroupName: json['RoleName']?.toString() ?? '',
      roles: json['RoleArea']?.toString() ?? '',
      roleId: json['RoleId']?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['roleId'] = roleId;
    data['roles'] = roles;
    data['roleGroupName'] = roleGroupName;
    return data;
  }
}
