///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LPNCondenseModel {
  String container;
  String po;
  String quantity;
  String itemName;
  String description;
  String binUpdatedBy;
  String binUpdatedDate;
  String scanId;


  LPNCondenseModel({
    required this.itemName,
    required this.description,
    required this.quantity,
    required this.binUpdatedBy,
    required this.binUpdatedDate,
    required this.container,
    required this.po,
    required this.scanId,
  });

  factory LPNCondenseModel.fromJson(List<dynamic> json) {
    return LPNCondenseModel(
      itemName: json[1]?.toString() ?? '',
      description: json[14]?.toString() ?? '',
      container: json[8]?.toString() ?? '',
      po: json[3]?.toString() ?? '',
      quantity: json[11]?.toString() ?? '',
      binUpdatedBy: json[29]?.toString() ?? '',
      binUpdatedDate: json[30]?.toString() ?? '',
      scanId: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itemName'] = itemName;
    data['description'] = description;
    data['quantity'] = quantity;
    data['binUpdatedBy'] = binUpdatedBy;
    data['binUpdatedDate'] = binUpdatedDate;
    data['container'] = container;
    data['po'] = po;
    data['scanId'] = scanId;
    return data;
  }
}
