///
/// Code generated by jsonwarehouseDartModel https://ashamp.github.io/jsonwarehouseDartModel/
///
class DriversMileageModel {
  String warehouse;
  String user;
  String totalRoutes;
  String totalStops;
  String totalMileage;

  DriversMileageModel({
    required this.user,
    required this.totalRoutes,
    required this.warehouse,
    required this.totalMileage,
    required this.totalStops,
  });

  factory DriversMileageModel.fromJson(List<dynamic> json) {
    return DriversMileageModel(
      user: json[1]?.toString() ?? '',
      totalRoutes: json[2]?.toString() ?? '',
      warehouse: json[10]?.toString() ?? '',
      totalMileage: json[10]?.toString() ?? '',
      totalStops: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user'] = user;
    data['totalRoutes'] = totalRoutes;
    data['warehouse'] = warehouse;
    data['totalMileage'] = totalMileage;
    data['totalStops'] = totalStops;
    return data;
  }
}
