///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ItemPickAverageModel {
  String itemCode;
  String legacyItem;
  String itemDescription;
  String unitPerCase;
  String qtyKPI;


  ItemPickAverageModel({
    required this.itemDescription,
    required this.qtyKPI,
    required this.unitPerCase,
    required this.legacyItem,
    required this.itemCode,
  });

  factory ItemPickAverageModel.fromJson(List<dynamic> json) {
    return ItemPickAverageModel(
      itemDescription: json[1]?.toString() ?? '',
      qtyKPI: json[10]?.toString() ?? '',
      unitPerCase: json[10]?.toString() ?? '',
      legacyItem: json[10]?.toString() ?? '',
      itemCode: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itemDescription'] = itemDescription;
    data['qtyKPI'] = qtyKPI;
    data['unitPerCase'] = unitPerCase;
    data['legacyItem'] = legacyItem;
    data['itemCode'] = itemCode;
    return data;
  }
}
