///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ToYardManagementModel {
  String to;
  String container;
  String containerItemType;
  String status;
  String memo;
  String fromWH;
  String toWH;
  String memoInYard;
  String dateInYard;
  String etaWarehouse;
  String inYardBy;
  String dock;
  String yardStatus;
  String receiveStart;
  String receiveStartBy;
  String driver;
  String unLoader;

  ToYardManagementModel({
    required this.container,
    required this.containerItemType,
    required this.toWH,
    required this.inYardBy,
    required this.dateInYard,
    required this.to,
    required this.etaWarehouse,
    required this.memoInYard,
    required this.fromWH,
    required this.status,
    required this.memo,
    required this.dock,
    required this.yardStatus,
    required this.receiveStart,
    required this.receiveStartBy,
    required this.driver,
    required this.unLoader,
  });

  factory ToYardManagementModel.fromJson(List<dynamic> json) {
    return ToYardManagementModel(
      container: json[2]?.toString() ?? '',
      containerItemType: json[2]?.toString() ?? '',
      toWH: json[10]?.toString() ?? '',
      inYardBy: json[10]?.toString() ?? '',
      dateInYard: json[10]?.toString() ?? '',
      to: json[10]?.toString() ?? '',
      etaWarehouse: json[10]?.toString() ?? '',
      memoInYard: json[10]?.toString() ?? '',
      fromWH: json[10]?.toString() ?? '',
      status: json[10]?.toString() ?? '',
      memo: json[10]?.toString() ?? '',
      dock: json[10]?.toString() ?? '',
      yardStatus: json[10]?.toString() ?? '',
      receiveStart: json[10]?.toString() ?? '',
      receiveStartBy: json[10]?.toString() ?? '',
      driver: json[10]?.toString() ?? '',
      unLoader: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['container'] = container;
    data['containerItemType'] = containerItemType;
    data['toWH'] = toWH;
    data['inYardBy'] = inYardBy;
    data['dateInYard'] = dateInYard;
    data['to'] = to;
    data['etaWarehouse'] = etaWarehouse;
    data['memoInYard'] = memoInYard;
    data['fromWH'] = fromWH;
    data['status'] = status;
    data['memo'] = memo;
    data['dock'] = dock;
    data['yardStatus'] = yardStatus;
    data['receiveStart'] = receiveStart;
    data['receiveStartBy'] = receiveStartBy;
    data['driver'] = driver;
    data['unLoader'] = unLoader;
    return data;
  }
}
