///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WarehouseUsageModel {
  String warehouse;
  String assignUser;
  String bpnBin;
  String notes;
  String itemCode;
  String onHand;
  String newQty;
  String createdBy;
  String createdDate;
  String nsAdjust;
  String adjustmentDate;
  String adjustmentBy;
  String mainMemo;
  String lineMemo;
  String legacyItem;
  String description;
  String qty;
  String pickBin;
  String avgCost;
  String estAmount;
  String classes;
  String wo;
  String purpose;
  String expenseCategory;
  String requestBy;
  String requestDate;
  String requestDepartment;
  String nsDepartment;
  String approvedBy;
  String approveDate;
  String approveDepartment;

  WarehouseUsageModel({
    required this.onHand,
    required this.assignUser,
    required this.bpnBin,
    required this.notes,
    required this.createdDate,
    required this.newQty,
    required this.nsAdjust,
    required this.adjustmentDate,
    required this.adjustmentBy,
    required this.warehouse,
    required this.mainMemo,
    required this.lineMemo,
    required this.createdBy,
    required this.itemCode,
    required this.legacyItem,
    required this.description,
    required this.qty,
    required this.pickBin,
    required this.avgCost,
    required this.estAmount,
    required this.classes,
    required this.wo,
    required this.purpose,
    required this.expenseCategory,
    required this.requestBy,
    required this.requestDate,
    required this.requestDepartment,
    required this.nsDepartment,
    required this.approvedBy,
    required this.approveDate,
    required this.approveDepartment,
  });

  factory WarehouseUsageModel.fromJson(List<dynamic> json) {
    return WarehouseUsageModel(
      warehouse: json[28]?.toString() ?? '',
      assignUser: json[28]?.toString() ?? '',
      onHand: json[14]?.toString() ?? '',
      bpnBin: json[8]?.toString() ?? '',
      notes: json[8]?.toString() ?? '',
      createdDate: json[26]?.toString() ?? '',
      newQty: json[23]?.toString() ?? '',
      nsAdjust: json[3]?.toString() ?? '',
      adjustmentDate: json[3]?.toString() ?? '',
      adjustmentBy: json[3]?.toString() ?? '',
      mainMemo: json[18]?.toString() ?? '',
      lineMemo: json[18]?.toString() ?? '',
      createdBy: json[18]?.toString() ?? '',
      itemCode: json[18]?.toString() ?? '',
      legacyItem: json[18]?.toString() ?? '',
      description: json[18]?.toString() ?? '',
      qty: json[18]?.toString() ?? '',
      pickBin: json[18]?.toString() ?? '',
      avgCost: json[18]?.toString() ?? '',
      estAmount: json[18]?.toString() ?? '',
      classes: json[18]?.toString() ?? '',
      wo: json[18]?.toString() ?? '',
      purpose: json[18]?.toString() ?? '',
      expenseCategory: json[18]?.toString() ?? '',
      requestBy: json[18]?.toString() ?? '',
      requestDate: json[18]?.toString() ?? '',
      requestDepartment: json[18]?.toString() ?? '',
      nsDepartment: json[18]?.toString() ?? '',
      approvedBy: json[18]?.toString() ?? '',
      approveDate: json[18]?.toString() ?? '',
      approveDepartment: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['onHand'] = onHand;
    data['assignUser'] = assignUser;
    data['bpnBin'] = bpnBin;
    data['notes'] = notes;
    data['createdDate'] = createdDate;
    data['newQty'] = newQty;
    data['nsAdjust'] = nsAdjust;
    data['adjustmentDate'] = adjustmentDate;
    data['adjustmentBy'] = adjustmentBy;
    data['warehouse'] = warehouse;
    data['mainMemo'] = mainMemo;
    data['lineMemo'] = lineMemo;
    data['createdBy'] = createdBy;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['description'] = description;
    data['qty'] = qty;
    data['pickBin'] = pickBin;
    data['avgCost'] = avgCost;
    data['estAmount'] = estAmount;
    data['classes'] = classes;
    data['wo'] = wo;
    data['purpose'] = purpose;
    data['expenseCategory'] = expenseCategory;
    data['requestBy'] = requestBy;
    data['requestDate'] = requestDate;
    data['requestDepartment'] = requestDepartment;
    data['nsDepartment'] = nsDepartment;
    data['approvedBy'] = approvedBy;
    data['approveDate'] = approveDate;
    data['approveDepartment'] = approveDepartment;
    return data;
  }
}
