///
/// Code generated by jsonwarehouseDartModel https://ashamp.github.io/jsonwarehouseDartModel/
///
class OrderScheduleModel {
  String warehouse;
  String pickStartedBy;
  String pickStarted;
  String so;
  String appointmentTimeDate;
  String customer;
  String pCompleted;
  String pCompletedBy;
  String shipVia;
  String auditStartedBy;
  String status;
  String shipDate;
  String auditStarted;
  String auditCompletedBy;
  String auditCompleted;

  OrderScheduleModel({
    required this.auditCompletedBy,
    required this.pickStartedBy,
    required this.pickStarted,
    required this.shipDate,
    required this.pCompleted,
    required this.status,
    required this.shipVia,
    required this.warehouse,
    required this.auditCompleted,
    required this.auditStarted,
    required this.auditStartedBy,
    required this.pCompletedBy,
    required this.customer,
    required this.so,
    required this.appointmentTimeDate,
  });

  factory OrderScheduleModel.fromJson(List<dynamic> json) {
    return OrderScheduleModel(
      pickStartedBy: json[1]?.toString() ?? '',
      pickStarted: json[2]?.toString() ?? '',
      auditCompletedBy: json[3]?.toString() ?? '',
      shipDate: json[5]?.toString() ?? '',
      pCompleted: json[10]?.toString() ?? '',
      status: json[10]?.toString() ?? '',
      shipVia: json[10]?.toString() ?? '',
      warehouse: json[10]?.toString() ?? '',
      auditStarted: json[10]?.toString() ?? '',
      auditCompleted: json[10]?.toString() ?? '',
      auditStartedBy: json[10]?.toString() ?? '',
      pCompletedBy: json[10]?.toString() ?? '',
      customer: json[10]?.toString() ?? '',
      so: json[10]?.toString() ?? '',
      appointmentTimeDate: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> warehouseJson() {
    final data = <String, dynamic>{};
    data['auditCompletedBy'] = auditCompletedBy;
    data['pickStartedBy'] = pickStartedBy;
    data['pickStarted'] = pickStarted;
    data['shipDate'] = shipDate;
    data['pCompleted'] = pCompleted;
    data['status'] = status;
    data['shipVia'] = shipVia;
    data['warehouse'] = warehouse;
    data['auditCompleted'] = auditCompleted;
    data['auditStarted'] = auditStarted;
    data['auditStartedBy'] = auditStartedBy;
    data['pCompletedBy'] = pCompletedBy;
    data['customer'] = customer;
    data['so'] = so;
    data['appointmentTimeDate'] = appointmentTimeDate;
    return data;
  }
}
