///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RecountBulkListModel {
  String lpn;
  String cycleCountID;
  String warehouse;
  String bin;
  String unitPerCase;
  String itemCode;
  String legacyItem;
  String pickQty;
  String lastRecountBy;
  String bpn;
  String lastRecountDate;
  String verifiedBy;
  String verifiedDate;
  String lastRecountQTY;


  RecountBulkListModel({
    required this.itemCode,
    required this.legacyItem,
    required this.bpn,
    required this.verifiedBy,
    required this.verifiedDate,
    required this.cycleCountID,
    required this.lastRecountDate,
    required this.unitPerCase,
    required this.warehouse,
    required this.pickQty,
    required this.lastRecountBy,
    required this.lpn,
    required this.bin,
    required this.lastRecountQTY,
  });

  factory RecountBulkListModel.fromJson(List<dynamic> json) {
    return RecountBulkListModel(
      itemCode: json[1]?.toString() ?? '',
      legacyItem: json[14]?.toString() ?? '',
      lpn: json[8]?.toString() ?? '',
      cycleCountID: json[25]?.toString() ?? '',
      warehouse: json[2]?.toString() ?? '',
      bin: json[3]?.toString() ?? '',
      unitPerCase: json[11]?.toString() ?? '',
      pickQty: json[29]?.toString() ?? '',
      lastRecountBy: json[30]?.toString() ?? '',
      bpn: json[4]?.toString() ?? '',
      lastRecountDate: json[32]?.toString() ?? '',
      verifiedBy: json[38]?.toString() ?? '',
      verifiedDate: json[18]?.toString() ?? '',
      lastRecountQTY: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['bpn'] = bpn;
    data['verifiedBy'] = verifiedBy;
    data['verifiedDate'] = verifiedDate;
    data['cycleCountID'] = cycleCountID;
    data['lastRecountDate'] = lastRecountDate;
    data['unitPerCase'] = unitPerCase;
    data['warehouse'] = warehouse;
    data['pickQty'] = pickQty;
    data['lastRecountBy'] = lastRecountBy;
    data['lpn'] = lpn;
    data['bin'] = bin;
    data['lastRecountQTY'] = lastRecountQTY;
    return data;
  }
}
