///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SPBPBatchDeleteModel {
  String so;
  String bp;
  String bpWh;
  String bpDate;

  SPBPBatchDeleteModel({
    required this.so,
    required this.bp,
    required this.bpDate,
    required this.bpWh,
  });

  factory SPBPBatchDeleteModel.fromJson(List<dynamic> json) {
    return SPBPBatchDeleteModel(
      bp: json[28]?.toString() ?? '',
      so: json[14]?.toString() ?? '',
      bpDate: json[18]?.toString() ?? '',
      bpWh: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['so'] = so;
    data['bp'] = bp;
    data['bpDate'] = bpDate;
    data['bpWh'] = bpWh;
    return data;
  }
}
