///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReceiveScanScannedItemModel {
  String scanId;
  String itemCode;
  String legacyItem;
  String description;
  String receivedQty;
  String bin;
  String receiveBy;
  String receiveDate;
  String createdBy;
  String createDate;

  ReceiveScanScannedItemModel({
    required this.itemCode,
    required this.legacyItem,
    required this.receiveBy,
    required this.createdBy,
    required this.scanId,
    required this.createDate,
    required this.receiveDate,
    required this.bin,
    required this.receivedQty,
    required this.description,
  });

  factory ReceiveScanScannedItemModel.fromJson(List<dynamic> json) {
    return ReceiveScanScannedItemModel(
      itemCode: json[1]?.toString() ?? '',
      legacyItem: json[2]?.toString() ?? '',
      receiveBy: json[10]?.toString() ?? '',
      createdBy: json[10]?.toString() ?? '',
      scanId: json[10]?.toString() ?? '',
      createDate: json[10]?.toString() ?? '',
      receiveDate: json[10]?.toString() ?? '',
      bin: json[10]?.toString() ?? '',
      receivedQty: json[10]?.toString() ?? '',
      description: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['receiveBy'] = receiveBy;
    data['createdBy'] = createdBy;
    data['scanId'] = scanId;
    data['createDate'] = createDate;
    data['receiveDate'] = receiveDate;
    data['bin'] = bin;
    data['receivedQty'] = receivedQty;
    data['description'] = description;
    return data;
  }
}
