///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReceiveScanWorkerAllocationModel {
  String userName;
  String dateTimeIn;
  String dateTimeOut;
  String addedBy;
  String addedDate;

  ReceiveScanWorkerAllocationModel({
    required this.dateTimeIn,
    required this.dateTimeOut,
    required this.userName,
    required this.addedDate,
    required this.addedBy,
  });

  factory ReceiveScanWorkerAllocationModel.fromJson(List<dynamic> json) {
    return ReceiveScanWorkerAllocationModel(
      dateTimeIn: json[1]?.toString() ?? '',
      dateTimeOut: json[2]?.toString() ?? '',
      userName: json[10]?.toString() ?? '',
      addedDate: json[10]?.toString() ?? '',
      addedBy: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['dateTimeIn'] = dateTimeIn;
    data['dateTimeOut'] = dateTimeOut;
    data['userName'] = userName;
    data['addedDate'] = addedDate;
    data['addedBy'] = addedBy;
    return data;
  }
}
