///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SoFulfillHistoryModel {
  String loc;
  String totalQty;
  String salesOrd;
  String pickStarted;
  String pickEnded;
  String kpiPar;
  String pickStartedBy;
  String shipDate;
  String items;
  String duration;
  String shipVia;
  String customerName;
  String pauseTimes;
  String orderStatus;
  String totalWeight;

  SoFulfillHistoryModel({
    required this.loc,
    required this.totalQty,
    required this.salesOrd,
    required this.pickStarted,
    required this.pickEnded,
    required this.kpiPar,
    required this.pickStartedBy,
    required this.shipDate,
    required this.items,
    required this.duration,
    required this.shipVia,
    required this.customerName,
    required this.pauseTimes,
    required this.orderStatus,
    required this.totalWeight,
  });

  factory SoFulfillHistoryModel.fromJson(List<dynamic> json) {
    return SoFulfillHistoryModel(
      loc: json[1]?.toString() ?? '',
      salesOrd: json[2]?.toString() ?? '',
      pickStarted: json[3]?.toString() ?? '',
      pickEnded: json[16]?.toString() ?? '',
      kpiPar: json[31]?.toString() ?? '',
      duration: json[30]?.toString() ?? '',
      pauseTimes: json[17]?.toString() ?? '',
      pickStartedBy: json[4]?.toString() ?? '',
      shipDate: json[3]?.toString() ?? '',
      items: json[6]?.toString() ?? '',
      totalQty: json[7]?.toString() ?? '',
      totalWeight: json[5]?.toString() ?? '',
      shipVia: json[9]?.toString() ?? '',
      customerName: json[11]?.toString() ?? '',
      orderStatus: json[12]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['loc'] = loc;
    data['totalQty'] = totalQty;
    data['salesOrd'] = salesOrd;
    data['pickStarted'] = pickStarted;
    data['pickEnded'] = pickEnded;
    data['kpiPar'] = kpiPar;
    data['pickStartedBy'] = pickStartedBy;
    data['shipDate'] = shipDate;
    data['items'] = items;
    data['duration'] = duration;
    data['shipVia'] = shipVia;
    data['customerName'] = customerName;
    data['pauseTimes'] = pauseTimes;
    data['orderStatus'] = orderStatus;
    data['totalWeight'] = totalWeight;
    return data;
  }
}
