///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SOFulfillHistoryExpansionNameModel {
  String wh;
  String oh;
  String avl;
  String ord;
  String backOrd;
  String commitedOrd;

  SOFulfillHistoryExpansionNameModel({
    required this.wh,
    required this.oh,
    required this.avl,
    required this.ord,
    required this.backOrd,
    required this.commitedOrd,
  });

  factory SOFulfillHistoryExpansionNameModel.fromJson(List<dynamic> json) {
    return SOFulfillHistoryExpansionNameModel(
      wh: json[0]?.toString() ?? '',
      oh: json[2]?.toString() ?? '',
      avl: json[1]?.toString() ?? '',
      ord: json[3]?.toString() ?? '',
      backOrd: json[4]?.toString() ?? '',
      commitedOrd: json[5]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['wh'] = wh;
    data['oh'] = oh;
    data['avl'] = avl;
    data['ord'] = ord;
    data['backOrd'] = backOrd;
    data['commitedOrd'] = commitedOrd;
    return data;
  }
}
