///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SOFulfillHistoryExpansionModel {
  String name;
  String bin;
  String description;
  String quantity;
  String filledQty;
  String balance;

  SOFulfillHistoryExpansionModel({
    required this.name,
    required this.bin,
    required this.description,
    required this.quantity,
    required this.filledQty,
    required this.balance,
  });

  factory SOFulfillHistoryExpansionModel.fromJson(List<dynamic> json) {
    return SOFulfillHistoryExpansionModel(
      name: json[1]?.toString() ?? '',
      bin: json[2]?.toString() ?? '',
      description: json[3]?.toString() ?? '',
      quantity: json[4]?.toString() ?? '',
      filledQty: json[5]?.toString() ?? '',
      balance: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['bin'] = bin;
    data['description'] = description;
    data['quantity'] = quantity;
    data['filledQty'] = filledQty;
    data['balance'] = balance;
    return data;
  }
}
