///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SPPackingQueueModel {
  String salesOrd;
  String bp;
  String pCompletedDate;
  String po;
  String customerName;
  String warehouse;
  String orderStatus;
  String shipToAddress;

  SPPackingQueueModel({
    required this.pCompletedDate,
    required this.salesOrd,
    required this.bp,
    required this.shipToAddress,
    required this.orderStatus,
    required this.warehouse,
    required this.customerName,
    required this.po,
  });

  factory SPPackingQueueModel.fromJson(List<dynamic> json) {
    return SPPackingQueueModel(
      bp: json[28]?.toString() ?? '',
      salesOrd: json[26]?.toString() ?? '',
      shipToAddress: json[18]?.toString() ?? '',
      orderStatus: json[3]?.toString() ?? '',
      warehouse: json[18]?.toString() ?? '',
      customerName: json[18]?.toString() ?? '',
      po: json[18]?.toString() ?? '',
      pCompletedDate: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pCompletedDate'] = pCompletedDate;
    data['salesOrd'] = salesOrd;
    data['bp'] = bp;
    data['shipToAddress'] = shipToAddress;
    data['orderStatus'] = orderStatus;
    data['warehouse'] = warehouse;
    data['customerName'] = customerName;
    data['po'] = po;
    data['pCompletedDate'] = pCompletedDate;
    return data;
  }
}
