///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BinCountCheckListModel {
  String lpn;
  String bin;
  String itemCode;
  String legacyItem;
  String area;
  String warehouse;
  String quantity;


  BinCountCheckListModel({
    required this.itemCode,
    required this.legacyItem,
    required this.warehouse,
    required this.bin,
    required this.lpn,
    required this.area,
    required this.quantity,
  });

  factory BinCountCheckListModel.fromJson(List<dynamic> json) {
    return BinCountCheckListModel(
      lpn: json[28]?.toString() ?? '',
      itemCode: json[2]?.toString() ?? '',
      legacyItem: json[14]?.toString() ?? '',
      warehouse: json[8]?.toString() ?? '',
      bin: json[23]?.toString() ?? '',
      area: json[18]?.toString() ?? '',
      quantity: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['warehouse'] = warehouse;
    data['bin'] = bin;
    data['lpn'] = lpn;
    data['area'] = area;
    data['quantity'] = quantity;
    return data;
  }
}
