///
/// Code generated by jsonwarehouseDartModel https://ashamp.github.io/jsonwarehouseDartModel/
///
class PickupSchedulModel {
  String warehouse;
  String customerName;
  String no;
  String so;
  String date;
  String weekday;
  String truckingCompany;
  String pallets;
  String action;
  String contact;
  String phone;
  String pickup;
  String note;
  String readyToShip;

  PickupSchedulModel({
    required this.readyToShip,
    required this.customerName,
    required this.no,
    required this.pickup,
    required this.truckingCompany,
    required this.phone,
    required this.action,
    required this.warehouse,
    required this.note,
    required this.contact,
    required this.pallets,
    required this.weekday,
    required this.so,
    required this.date,
  });

  factory PickupSchedulModel.fromJson(List<dynamic> json) {
    return PickupSchedulModel(
      customerName: json[1]?.toString() ?? '',
      no: json[2]?.toString() ?? '',
      readyToShip: json[3]?.toString() ?? '',
      pickup: json[5]?.toString() ?? '',
      truckingCompany: json[10]?.toString() ?? '',
      phone: json[10]?.toString() ?? '',
      action: json[10]?.toString() ?? '',
      warehouse: json[10]?.toString() ?? '',
      note: json[10]?.toString() ?? '',
      contact: json[10]?.toString() ?? '',
      pallets: json[10]?.toString() ?? '',
      weekday: json[10]?.toString() ?? '',
      so: json[10]?.toString() ?? '',
      date: json[10]?.toString() ?? '',
    );
  }

  Map<String, dynamic> warehouseJson() {
    final data = <String, dynamic>{};
    data['readyToShip'] = readyToShip;
    data['customerName'] = customerName;
    data['no'] = no;
    data['pickup'] = pickup;
    data['truckingCompany'] = truckingCompany;
    data['phone'] = phone;
    data['action'] = action;
    data['warehouse'] = warehouse;
    data['note'] = note;
    data['contact'] = contact;
    data['pallets'] = pallets;
    data['weekday'] = weekday;
    data['so'] = so;
    data['date'] = date;
    return data;
  }
}
