///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QueueExpansionModel {
  String name;
  String legacyItem;
  String description;
  String quantity;
  String filledQty;
  String balance;

  QueueExpansionModel({
    required this.name,
    required this.legacyItem,
    required this.description,
    required this.quantity,
    required this.filledQty,
    required this.balance,
  });

  factory QueueExpansionModel.fromJson(List<dynamic> json) {
    return QueueExpansionModel(
      name: json[1]?.toString() ?? '',
      legacyItem: json[8]?.toString() ?? '',
      description: json[3]?.toString() ?? '',
      quantity: json[4]?.toString() ?? '',
      filledQty: json[5]?.toString() ?? '',
      balance: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['legacyItem'] = legacyItem;
    data['description'] = description;
    data['quantity'] = quantity;
    data['filledQty'] = filledQty;
    data['balance'] = balance;
    return data;
  }
}
