///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QueueModel {
  String salesOrder;
  String priority;
  String totalCube;
  String shipDate;
  String shipVia;
  String shipAddress;
  String customerName;
  String orderStatus;
  String pickStarted;
  String pickStartedBy;
  String shipState;
  String shipZipCode;
  String id;
  String committedBy;
  String committedDate;
  String pCompleteBy;
  String pCompleteDate;
  String salesShipID;
  String invoice;
  String shipCity;
  String shipAddress1;
  String shipAddress2;
  String loaderAssignTo;
  String totalWeight;
  String duration;
  String items;
  String billingDate;
  String billingBy;
  String auditDate;
  String auditBy;
  String warehouse;
  String truckNo;
  String routeStop;
  String pickTime;
  String expectedPickTime;
  String caseQTY;
  String ltlPalletQty;
  String tlPalletQty;
  String pickerAssignedTo;
  String pullers;
  String totalQty;

  QueueModel({
    required this.salesOrder,
    required this.priority,
    required this.totalCube,
    required this.shipDate,
    required this.shipVia,
    required this.shipAddress,
    required this.customerName,
    required this.orderStatus,
    required this.pickStarted,
    required this.pickStartedBy,
    required this.shipState,
    required this.shipZipCode,
    required this.id,
    required this.committedBy,
    required this.committedDate,
    required this.pCompleteBy,
    required this.pCompleteDate,
    required this.salesShipID,
    required this.invoice,
    required this.shipCity,
    required this.shipAddress1,
    required this.shipAddress2,
    required this.loaderAssignTo,
    required this.totalWeight,
    required this.duration,
    required this.items,
    required this.billingDate,
    required this.billingBy,
    required this.auditDate,
    required this.auditBy,
    required this.warehouse,
    required this.truckNo,
    required this.routeStop,
    required this.pickTime,
    required this.expectedPickTime,
    required this.caseQTY,
    required this.ltlPalletQty,
    required this.tlPalletQty,
    required this.pickerAssignedTo,
    required this.pullers,
    required this.totalQty,
  });

  factory QueueModel.fromJson(Map<String, dynamic> json) {
    return QueueModel(
      salesOrder: json['TransactionId']?.toString() ?? '',
      priority: json['Priority']?.toString() ?? '',
      totalCube: json['TotalCube']?.toString() ?? '',
      shipDate: json['ShipDate']?.toString() ?? '',
      shipVia: json['ShipVia']?.toString() ?? '',
      shipAddress: json['ShipAddress']?.toString() ?? '',
      customerName: json['CustomerName']?.toString() ?? '',
      orderStatus: json['Status']?.toString() ?? '',
      pickStarted: json['PickStarted']?.toString() ?? '',
      pickStartedBy: json['PickStartedBy']?.toString() ?? '',
      shipState: json['ShipState']?.toString() ?? '',
      shipZipCode: json['ShipZipCode']?.toString() ?? '',
      id: json['Id']?.toString() ?? '',
      committedBy: json['CommittedBy']?.toString() ?? '',
      committedDate: json['CommittedDate']?.toString() ?? '',
      pCompleteBy: json['PCompleteBy']?.toString() ?? '',
      pCompleteDate: json['PCompleteDate']?.toString() ?? '',
      salesShipID: json['SalesShipID']?.toString() ?? '',
      shipCity: json['ShipCity']?.toString() ?? '',
      shipAddress1: json['ShipAddress1']?.toString() ?? '',
      shipAddress2: json['ShipAddress2']?.toString() ?? '',
      loaderAssignTo: json['LoaderAssignTo']?.toString() ?? '',
      totalWeight: json['TotalWeight']?.toString() ?? '',
      duration: json['Duration']?.toString() ?? '',
      items: json['ItemCount']?.toString() ?? '',
      billingDate: json['BillingDate']?.toString() ?? '',
      billingBy: json['BillingBy']?.toString() ?? '',
      auditDate: json['AuditDate']?.toString() ?? '',
      auditBy: json['AuditBy']?.toString() ?? '',
      warehouse: json['Warehouse']?.toString() ?? '',
      truckNo: json['TruckNo']?.toString() ?? '',
      routeStop: json['RouteStop']?.toString() ?? '',
      pickTime: json['PickTime']?.toString() ?? '',
      expectedPickTime: json['ExpectedPickTime']?.toString() ?? '',
      caseQTY: json['ECommerce']?.toString() ?? '',
      invoice: json['Invoice']?.toString() ?? '',
      ltlPalletQty: json['LTLPalletCount']?.toString() ?? '',
      tlPalletQty: json['TotalTLPalletCount']?.toString() ?? '',
      pickerAssignedTo: json['PickerAssignedTo']?.toString() ?? '',
      pullers: json['Pullers']?.toString() ?? '',
      totalQty: json['TotalQty']?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['salesOrder'] = salesOrder;
    data['priority'] = priority;
    data['totalCube'] = totalCube;
    data['shipDate'] = shipDate;
    data['shipVia'] = shipVia;
    data['shipAddress'] = shipAddress;
    data['customerName'] = customerName;
    data['orderStatus'] = orderStatus;
    data['pickStarted'] = pickStarted;
    data['pickStartedBy'] = pickStartedBy;
    data['shipState'] = shipState;
    data['shipZipCode'] = shipZipCode;
    data['Id'] = id;
    data['committedBy'] = committedBy;
    data['committedDate'] = committedDate;
    data['pCompleteBy'] = pCompleteBy;
    data['pCompleteDate'] = pCompleteDate;
    data['salesShipID'] = salesShipID;
    data['invoice'] = invoice;
    data['shipCity'] = shipCity;
    data['shipAddress1'] = shipAddress1;
    data['shipAddress2'] = shipAddress2;
    data['loaderAssignTo'] = loaderAssignTo;
    data['totalWeight'] = totalWeight;
    data['duration'] = duration;
    data['items'] = items;
    data['billingDate'] = billingDate;
    data['billingBy'] = billingBy;
    data['auditDate'] = auditDate;
    data['auditBy'] = auditBy;
    data['warehouse'] = warehouse;
    data['truckNo'] = truckNo;
    data['routeStop'] = routeStop;
    data['pickTime'] = pickTime;
    data['expectedPickTime'] = expectedPickTime;
    data['caseQTY'] = caseQTY;
    data['ltlPalletQty'] = ltlPalletQty;
    data['tlPalletQty'] = tlPalletQty;
    data['pickerAssignedTo'] = pickerAssignedTo;
    data['pullers'] = pullers;
    data['totalQty'] = totalQty;
    return data;
  }
}
