///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QueueExpansionBinModel {
  String bin;
  String license;
  String quantity;

  QueueExpansionBinModel({
    required this.bin,
    required this.license,
    required this.quantity,
  });

  factory QueueExpansionBinModel.fromJson(List<dynamic> json) {
    return QueueExpansionBinModel(
      bin: json[0]?.toString() ?? '',
      license: json[1]?.toString() ?? '',
      quantity: json[2]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['license'] = license;
    data['quantity'] = quantity;
    return data;
  }
}
