///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InventoryCountProgressDashboardModel {
  String ccId;
  String createdBy;
  String createdDate;
  String futureCountDate;
  String isRecount;
  String startTime;
  String duration;


  InventoryCountProgressDashboardModel({
    required this.ccId,
    required this.futureCountDate,
    required this.isRecount,
    required this.createdBy,
    required this.createdDate,
    required this.startTime,
    required this.duration,
  });

  factory InventoryCountProgressDashboardModel.fromJson(List<dynamic> json) {
    return InventoryCountProgressDashboardModel(
      isRecount: json[8]?.toString() ?? '',
      ccId: json[4]?.toString() ?? '',
      futureCountDate: json[32]?.toString() ?? '',
      createdBy: json[6]?.toString() ?? '',
      createdDate: json[6]?.toString() ?? '',
      startTime: json[6]?.toString() ?? '',
      duration: json[6]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ccId'] = ccId;
    data['futureCountDate'] = futureCountDate;
    data['startTime'] = startTime;
    data['duration'] = duration;
    data['isRecount'] = isRecount;
    data['createdBy'] = createdBy;
    data['createdDate'] = createdDate;
    return data;
  }
}
