///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PrecountListModel {
  String warehouse;
  String countDate;
  String bin;
  String itemCode;
  String finishedDate;
  String bpn;
  String countPage;
  String legacyItem;
  String futureCountDate;
  String license;
  String countQTY;
  String countBy;

  PrecountListModel({
    required this.bin,
    required this.countDate,
    required this.finishedDate,
    required this.warehouse,
    required this.bpn,
    required this.countPage,
    required this.itemCode,
    required this.legacyItem,
    required this.futureCountDate,
    required this.license,
    required this.countQTY,
    required this.countBy,
  });

  factory PrecountListModel.fromJson(List<dynamic> json) {
    return PrecountListModel(
      warehouse: json[28]?.toString() ?? '',
      countDate: json[28]?.toString() ?? '',
      bin: json[14]?.toString() ?? '',
      finishedDate: json[26]?.toString() ?? '',
      bpn: json[18]?.toString() ?? '',
      countPage: json[18]?.toString() ?? '',
      itemCode: json[18]?.toString() ?? '',
      legacyItem: json[18]?.toString() ?? '',
      futureCountDate: json[18]?.toString() ?? '',
      license: json[18]?.toString() ?? '',
      countQTY: json[18]?.toString() ?? '',
      countBy: json[18]?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bin'] = bin;
    data['countDate'] = countDate;
    data['finishedDate'] = finishedDate;
    data['warehouse'] = warehouse;
    data['bpn'] = bpn;
    data['countPage'] = countPage;
    data['itemCode'] = itemCode;
    data['legacyItem'] = legacyItem;
    data['futureCountDate'] = futureCountDate;
    data['license'] = license;
    data['countQTY'] = countQTY;
    data['countBy'] = countBy;
    return data;
  }
}
